### ISSUE TITLE
[Feature Request] Ports in "View Application"-page

### ISSUE THREAD

**Issue by Griefed** [SelfhostedPro/Yacht#100]
If feasible, I'd love to see the following addition to the "View Applications" page:

Ports on the host and container in the usual host:container format, for each app. An example can be seen in portainer:
![image](https://user-images.githubusercontent.com/44273438/94045258-85055c00-fdcf-11ea-853e-c799e63258f5.png)

Copy pasted from original issue #77 as per the wish of SelfhostedPro.

**Comment by SelfhostedPro** [comment]
Currently it shows the port on the host and generates a link to that port (not on the backend) would it be better to show both or do you think just the one you can access it on is better?

**Comment by SelfhostedPro** [comment]
I'll eventually be replacing it with the description of the port (if there is one) once https://github.com/SelfhostedPro/Yacht/issues/73 is implemented

**Comment by Griefed** [comment]
Personally, I'm a fan of "More information is better", but I can see why someone else would say "I only care about ports mapped to the host, since they're the ones I'll be accessing from external".
It's not necessary to know the internal ports, one can always look them up if they're so inclined, so just the ones you can access should be fine.

Curious to see the port description feature and some examples in action.
