### ISSUE TITLE
[Feature Request] Customizable column views in "View Applications"-page

### ISSUE THREAD

**Issue by Griefed** [SelfhostedPro/Yacht#102]
Allow users to specify the columns displayed. For example: Only show "Name", "Status", "Ports" & hide "Stack","Image", "Created At". Allows for more personalization, me thinks.

![image](https://user-images.githubusercontent.com/44273438/94046028-6b184900-fdd0-11ea-8923-852e4b3cbba7.png)
![image](https://user-images.githubusercontent.com/44273438/94046123-900cbc00-fdd0-11ea-81c9-343b7e38e8c3.png)
![image](https://user-images.githubusercontent.com/44273438/94046172-a3b82280-fdd0-11ea-9d49-5d0d0c8a1401.png)

Copy pasted from original issue #77 as per the wish of SelfhostedPro.

**Comment by SelfhostedPro** [comment]
Does this need to be persistent or would it be alright if it's needed to be set every time? (Want to avoid putting this in a db if possible, may use browser storage)
Example here:
https://codepen.io/chansv/pen/PooKMNb

**Comment by Griefed** [comment]
While persistence would be pretty sweet, setting a cookie or something would be fine, too. If one can edit a config to set the "default" view, that would be a way of handling it, too.

**Comment by SelfhostedPro** [comment]
If I use browser storage it should stay set for quite a while. Currently there's not a Yacht config file per say (using a database for any settings).

**Comment by SelfhostedPro** [comment]
Added for Alpha 4. Will be built in the devel branch in ~ an hour. Currently it's not persistent but I'll work on adding that functionality.

**Comment by Griefed** [comment]
Works like a charm. Looking forward to persistency.
Thank you very much and keep up the good work!
