### ISSUE TITLE
[Suggestion] Colour-coding containers on "View Applications"-page for further sorting

### ISSUE THREAD

**Issue by Griefed** [SelfhostedPro/Yacht#103]
The following is an idea only, not a full on suggestion. Would love your feedback on it.
Colour-coding containers:
In case someone has many containers running, like on my system with currently 28 containers, somehow grouping or identifying them by colour, for example, would be nice. Give all container names which serve websites like wordpress or apache a red background, all container names with containers which serve media a green background. Could be done of a stack by stack basis. Stack A=red, stack B=blue, stack C=green. Much like Portainer displays the state of containers, "running" has a green background. I hope I made sense here. English isn't my first languange, sorry.

Copy pasted from original issue #77 as per the wish of SelfhostedPro.

**Comment by SelfhostedPro** [comment]
I may have the user do this manually via labels once https://github.com/SelfhostedPro/Yacht/issues/106 is implemented.

**Comment by wickedyoda** [comment]
See issue #106 and open a new ticket if labeling and color-coding still need to be addressed further.
