### ISSUE TITLE
[Feature Request] Add container label support

### ISSUE THREAD

**Issue by blathers123** [SelfhostedPro/Yacht#106]
Allowing users to add labels to containers will allow traefik to automatically discover the containers. 
It would be nice to be able to define some default labels for all containers, and then edit them on a per container basis

**Comment by SelfhostedPro** [comment]
Do you have an idea of what the default labels should be or should that be a server setting?

**Comment by blathers123** [comment]
That should definitely be a server setting, I think everyone's setup, use case, and software versions are going to be too different to have pre-defined labels.

**Comment by SelfhostedPro** [comment]
Fair enough. I'll go ahead and add this to the list.

**Comment by SelfhostedPro** [comment]
Added
