### ISSUE TITLE
Support for Docker Socket Proxy

### ISSUE THREAD

**Issue by tehniemer** [SelfhostedPro/Yacht#107]
I keep access to the docker socket behind a proxy, so mapping /var/run/docker.sock doesn't work for my use case. Instead, all of my containers that need access to the docker socket get access through tcp://socket-proxy:2375 via a specific command or environment variable. I'd like to give this a shot to compare to portainer, but won't be able to until this is supported. 

https://github.com/fluencelabs/docker-socket-proxy

**Comment by SelfhostedPro** [comment]
The built in env variable DOCKER_HOST may do what you want. Documentation on it is available here: https://docs.docker.com/engine/reference/commandline/cli/#environment-variables
Not the recommended way to do things but it may work for you for now.

**Comment by tehniemer** [comment]
I did not realize that was a built in variable, I've used it in other containers, but I always thought that was container specific. Thanks for the info, that got me going.
