### ISSUE TITLE
[Feature Request] Start line/compose parsing to template.

### ISSUE THREAD

**Issue by thesugarat** [SelfhostedPro/Yacht#113]
I would like an interface where I can paste in a container start line: 

docker run -d -p 8000:8000 -v /var/run/docker.sock:/var/run/docker.sock -v yacht:/config selfhostedpro/yacht

After hitting enter or clicking a Go button, the parser should identify each part of the syntax and place it in a new template that can be further edited/saved/executed. Ideally the parser should read start lines and/or compose syntax for template creation.

**Comment by SelfhostedPro** [comment]
We've already got a template syntax if you want to gradually modify a container configuration (uses YAML or json and documentation is in the wiki) I could look into building an external tool (onto https://ycht.tech) to convert a docker run command into a template if that would fit your needs but I don't feel as though this fits into the ease of use ideology part of Yacht and would be difficult to implement via docker-py. 

If you think of a good way you could always submit a PR though. 

Let me know if the external tool would be of interest to you.

**Comment by SelfhostedPro** [comment]
If you're alright with a CLI tool this may be worth a look:
https://github.com/lavie/runlike/

**Comment by SelfhostedPro** [comment]
I recently released shipwright which is a graphical template builder if that's more your speed.
