### ISSUE TITLE
[Feature Request] Disable Authentication/Login

### ISSUE THREAD

**Issue by ducky710** [SelfhostedPro/Yacht#121]
A way to disable the login/auth similiar to portainers "--no-auth" command be great for those of us who use SSO's like Authelia.

**Comment by SelfhostedPro** [comment]
I will probably implement this as an environment variable. Added to the Alpha to-do.

**Comment by ducky710** [comment]
Awesome thanks!

**Comment by SelfhostedPro** [comment]
Once Alpha 4 is released you can disable authentication by setting `DISABLE_AUTH=True` as an environment variable. If you would like to test this out try the devel branch once it's done building the latest merge.

**Comment by ducky710** [comment]
Hey thanks for adding this so quickly! Going to test it out as soon as I get the chance!

**Comment by yangkghjh** [comment]
Is there a plan to add `remember me` function to login page?

**Comment by SelfhostedPro** [comment]
> Is there a plan to add `remember me` function to login page?

I'll look into adding one. I may wind up using a different authentication framework eventually but the remember me function will likely be a little while out as it's not easy with the current framework. The other issue is that Yacht uses a different secret key everytime it restarts so it will kick you out of your session. Please open a separate issue for this so I can keep an eye on it when this one closes.
