### ISSUE TITLE
[Feature Request] Ability to pull & deploy new (latest) image of a already deployed container

### ISSUE THREAD

**Issue by ank0m** [SelfhostedPro/Yacht#131]
It would be nice if there is a way to pull and deploy the latest image for a running container out of Yacht. 

Yes, there is Watchtower which offers this ability and I'm already using it in "check-only-mode" as I want to be in control of if/when a container shall be updated.

Right now I have to use CLI and stop/remove a container, pull the latest image and deploy it again, or didn't I realise that there is a way from within Yacht right now?

**Comment by SelfhostedPro** [comment]
Check out the devel tag. I've added updates there. When you click on the update button it runs watchtower with the --run-once tag and adds the name of the container you're updating to the targets. Essentially this allows for 1 click updates utilizing watchtower (you don't need to have it deployed as it will spin up its own instance).

**Comment by ank0m** [comment]
That sounds fantastic, will give it a try when I'm back home.
