### ISSUE TITLE
[Feature Request] Add Container Controllbuttons inside the App Page

### ISSUE THREAD

**Issue by ptTrR** [SelfhostedPro/Yacht#135]
Adding Buttons inside the Container/App Page for "Restart;Stop;Start;Delete" - Maybe also the option to update all containers or every container it self

**Comment by SelfhostedPro** [comment]
Just made the change. Once that pull  request goes through it will be ready when the next release comes out.

**Comment by SelfhostedPro** [comment]
Merged into master.
