### ISSUE TITLE
Can't View dashboard anymore

### ISSUE THREAD

**Issue by aryehassbian** [SelfhostedPro/Yacht#137]
I have been using it for a while and everything went well. But Now I can NOT view the dashboard anymore.
Is there any limitation on Dockers count? I have up to 110 Dockers now. I was able to use dashboard before the upgrade of 4 or 5 new Dockers.
Any idea? thanks

**Comment by SelfhostedPro** [comment]
Can you please post logs from your yacht container when you try to view the dashboard? Can you also provide browser console logs (hit f12 and click on console when you go to the dashboard)?

**Comment by SelfhostedPro** [comment]
Also, are you accessing Yacht via a reverse proxy?

**Comment by mrancier** [comment]
I am having the same issue.  I just installed.  And yes, I am trying to access yacht through a reverse proxy.  If I go the Http:port way, all the dashboard stats and logs work.  Through the proxy, they do not display.  Is there a workaround ?
Thanks.

**Comment by SelfhostedPro** [comment]
There isn't currently a work around. I'm working on resolving this but for now dashboards are unavailable via reverse proxy per https://github.com/SelfhostedPro/Yacht/issues/72

**Comment by mrancier** [comment]
Thank you so much for the info.

**Comment by SelfhostedPro** [comment]
Merging with #144
