### ISSUE TITLE
Not able to see my Dashboard any more Reaching over 100 Dockers

### ISSUE THREAD

**Issue by aryehassbian** [SelfhostedPro/Yacht#144]
Hi, 
I have been using Yacht for the last couple of days. Everything works OK till I added a couple of Dockers too many.
At this point I can NOT see anything in the Dashboard BUT the word Status and a Refresh Arrow.
Doing F12 - Getting this Error:
```
Error: Request failed with status code 401
    at t.exports (createError.js:16)
    at t.exports (settle.js:17)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:69)
Home.vue:85 Starting connection to Websocket
```
Not sure what type of Authorization is needed and How I am violating it?
Please assist.
Thanks

**Comment by SelfhostedPro** [comment]
If you're getting a 401 try clearing your browser cache. Do the logs on the yacht container say anything? (`docker logs <container id>`)

**Comment by SelfhostedPro** [comment]
There is no hard limit on the number of containers you have. Please reply here instead of opening a new issue when you reply.

**Comment by SelfhostedPro** [comment]
Any updates on this?

**Comment by SelfhostedPro** [comment]
Hey, are you still having this issue? If not please let me know so I can close this.

**Comment by SelfhostedPro** [comment]
Closing due to no contact. If you get a chance to reply or if anyone else has this issue, let me know and I'll reopen it.
