### ISSUE TITLE
Make notes more prominent in the deployment process

### ISSUE THREAD

**Issue by geekedtv** [SelfhostedPro/Yacht#148]
When deploying apps from the template, notes do not appear visible. I am either missing something or notes are just not visible. Can you sticky the notes for apps at the top of each deployment step? Notes hold critical information about the apps such as login details.

**Comment by SelfhostedPro** [comment]
Once the linked pull request is merged this will be added to master. In the meantime this is building in the devel tag and will be ready in ~an hour.
