### ISSUE TITLE
[Feature Request]Support network_mode

### ISSUE THREAD

**Issue by yangkghjh** [SelfhostedPro/Yacht#155]

**Comment by SelfhostedPro** [comment]
Thanks for the suggestion! I'm currently working on building out the image/volume/network managment parts of the UI, once I've got those going I'll get support for network_mode and a few other networking settings implemented. I'll link the PR once I merge into develop for testing.

**Comment by SelfhostedPro** [comment]
This is supported with the latest release. It should be done building in ~40-50 minutes. If you run into any issues let me know and I'll re-open this.
