### ISSUE TITLE
add an option to put apps into a second net other than bridge by default. 

### ISSUE THREAD

**Issue by bayeslearner** [SelfhostedPro/Yacht#159]
Hi, 
It would be really nice if this option is available.  I'm using nginx proxy manager so that I don't have to remember all these different ports.  However, the default bridge won't allow containers to see each other without explicitly linking.  

I had to use portainer to attach container apps into a second network for nginx proxy manager to work.

**Comment by SelfhostedPro** [comment]
Network managment is currently a WIP. I'm hoping to finish it up this week. Finished images today, will be working on volumes next, and then networking.

Once network managment is implemented the more advanced networking settings will become available when deploying an application. I'll reply here once the pull request is in.

**Comment by SelfhostedPro** [comment]
If you want to test the devel branch, you can manage networks and when deploying a container you can attach it to said network. I'll work on adding networks to running containers as well.

**Comment by SelfhostedPro** [comment]
Should be doable with the latest release. Please let me know if you have any issues and I'll re-open.
