### ISSUE TITLE
 Internal Server Error: error while creating mount source path '/yacht/AppData/Config/Heimdall': mkdir /yacht: read-only file system 

### ISSUE THREAD

**Issue by tegralens** [SelfhostedPro/Yacht#160]
Fresh install of Ubuntu 20.04. I then did all the updates and upgrades and install Yacht. but while i was trying to deploy Heimdall I received the error below.

 Internal Server Error: error while creating mount source path '/yacht/AppData/Config/Heimdall': mkdir /yacht: read-only file system

I tried another template called Nginx proxy manager and that also gave me an error.

It's probably cause Yacht doesn't have sudo rights.

**Comment by SelfhostedPro** [comment]
Yacht doesn't need sudo rights as long as your user is in the docker group. Try checking permissions for that directory. You can set the PUID and PGID variables for Yacht to match your user (you can find your values using the `id` command) just like the LSIO containers. .

**Comment by tegralens** [comment]
I noticed I didnt do a few things on the docker site like adding my user name and other things. That part is important so that it works. But since I added Docker a different way it was not working right. After installing it again with the way the docker site said then it works fine. Thanks
