### ISSUE TITLE
Unprocessable Entity error when changing user email address to a non valid email address

### ISSUE THREAD

**Issue by marchah** [SelfhostedPro/Yacht#193]
I get this error when i try to change the email address from `admin@yacht.local` to just `admin`

<img width="285" alt="Screen Shot 2020-10-22 at 12 01 04 PM" src="https://user-images.githubusercontent.com/818848/96917879-48746100-145e-11eb-8c46-2d14f8e3fc89.png">

Not really a big deal just wanted to let you know

**Comment by SelfhostedPro** [comment]
Yes, you need to use a valid email address there (at least in the format ie. something@test.test). It's a limitation of the auth framework I'm using. I'll leave this open to remind me to add client side validation before you can submit.
