### ISSUE TITLE
Internal Server Error when adding Template Env Var

### ISSUE THREAD

**Issue by marchah** [SelfhostedPro/Yacht#194]
I added the env var one by one, the issue is happening when i try to add `!PGID`, it doesn't like when the replacement value already exist, if i change it it's working fine

<img width="1360" alt="Screen Shot 2020-10-22 at 12 41 15 PM" src="https://user-images.githubusercontent.com/818848/96921979-19f98480-1464-11eb-8c71-dde1b679a32d.png">

**Comment by SelfhostedPro** [comment]
Looks like I had replacement set as a unique constraint. I removed the unique requirement. Once this build is done it will be available on the :devel branch for testing: https://github.com/SelfhostedPro/Yacht/runs/1294646601?check_suite_focus=true

**Comment by SelfhostedPro** [comment]
Can you try with the devel branch and let me know if that's working for you?
