### ISSUE TITLE
[Community Thread] General Frontend (UI) Discussion. 

### ISSUE THREAD

**Issue by SelfhostedPro** [SelfhostedPro/Yacht#206]
Think it would be good to have a general UI discussion. If there's something discussed that I want to implement I'll open a new issue and link it to this one. 

Just wanted to try having this here instead of a dedicated forum so people don't have to make another account.

**Comment by gmerrall** [comment]
Some way to edit an existing container would be helpful. I set up [Transmission/OpenVPN](https://hub.docker.com/r/haugene/transmission-openvpn) recently on a OMV install which has a lot of environment variables and it took a bit of of fiddling to get right. Now if I want to adjust any settings I have to remove the app and recreate it from scratch.

One option I could use would be using a template and that's totally fine for more complex setups like Transmission/OpenVPN, but for simpler installs having to create/edit a template and remove/recreate an app seems like a lot of work if all you want to do is modify/add a setting.

**Comment by SelfhostedPro** [comment]
This is definitely on the Todo list. Will leave this open and let you know when it's in.

**Comment by junaid2314** [comment]
Hi, how can I create Yacht templates myself which are not on yacht. I know some already there on yacht but some of not there.​​https://awesomeopensource.com/project/awesome-selfhosted/awesome-selfhosted
   https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/yacht/Template/template.json
thanks

**Comment by gmerrall** [comment]
>
> Please refer to the documentation on how to create a template. Then you
> just need to have the template hosted somewhere, got example here on github.

In the templates section of the UI, enter the URL and you're done.

**Comment by junaid2314** [comment]
@gmerrall thanks for reply can you share documentation link  where i can look for templates creation related guide.

**Comment by SelfhostedPro** [comment]
> @gmerrall thanks for reply can you share documentation link where i can look for templates creation related guide.

Here you go: https://yacht.sh/Templates/templates/

You can do either json or YAML. I recommend yaml for newcomers. GUI tool for making them is a WIP.

**Comment by SelfhostedPro** [comment]
> Some way to edit an existing container would be helpful. I set up [Transmission/OpenVPN](https://hub.docker.com/r/haugene/transmission-openvpn) recently on a OMV install which has a lot of environment variables and it took a bit of of fiddling to get right. Now if I want to adjust any settings I have to remove the app and recreate it from scratch.
> 
> One option I could use would be using a template and that's totally fine for more complex setups like Transmission/OpenVPN, but for simpler installs having to create/edit a template and remove/recreate an app seems like a lot of work if all you want to do is modify/add a setting.

This feature has been added.

**Comment by michaelhthomas** [comment]
Here's a random small tweak that I think would help make the application interface a bit easier to navigate (and more colorful), color coded action buttons:
![image](https://user-images.githubusercontent.com/18223295/132581109-d04b077c-2d65-4610-9749-6c2d2ac53b26.png)
Thoughts?

**Comment by michaelhthomas** [comment]
Maybe something like this for container statuses as well:
![image](https://user-images.githubusercontent.com/18223295/132585273-f1d3f272-8870-4e85-889e-86c5bd16ed7a.png)

**Comment by SelfhostedPro** [comment]
> Maybe something like this for container statuses as well:
> 
> ![image](https://user-images.githubusercontent.com/18223295/132585273-f1d3f272-8870-4e85-889e-86c5bd16ed7a.png)
> 
> 

Both of those are easy changes to make if they're wanted. I didn't do that since I didn't want to prevent someone from theming them but if people want that I could do it. Anyone have a good idea as far as a poll for that or should we just let 👍 on your comment for who wants it and 👎 for no?
