### ISSUE TITLE
500 Error when changing email address

### ISSUE THREAD

**Issue by curator888** [SelfhostedPro/Yacht#21]
When I change my email I get a 500 Error message, this might be because my emails ends in .rocks and not the anticipated .com .etc.

**Comment by SelfhostedPro** [comment]
In the meantime you can change it in the user dashboard by selecting manage users and selecting your user, then changing the email. This is due to the removal of redis. There's currently no email functionality and I must have missed fixing this section.

**Comment by SelfhostedPro** [comment]
Fixed in ab0a9af913d7cf33f64fc6c3a48ea498b6c4992a waiting for build to pass and then merging with master.
