### ISSUE TITLE
Unable to load UI

### ISSUE THREAD

**Issue by hibare** [SelfhostedPro/Yacht#217]
```
docker run -d -p 8000:8000 -v /var/run/docker.sock:/var/run/docker.sock -v yacht:/config selfhostedpro/yacht
```

Above commands gives empty page.

Looking at browser console, found some errors.

![Screenshot from 2020-11-16 20-16-37](https://user-images.githubusercontent.com/20609766/99266819-31e8dc00-2849-11eb-8c1b-9d57e95aed8f.jpg)

**Comment by hibare** [comment]
Some more details.

Image: latest
OS: Ubuntu 64bit

**Comment by SelfhostedPro** [comment]
Hmm, none of those errors should be preventing it from loading. What browser are you using? Are there any logs for Yacht?

**Comment by hibare** [comment]
Browser: firefox

No logs from yatch in console

**Comment by SelfhostedPro** [comment]
Well, I can verify that it's working in Firefox alright as that's what I develop on. Can you paste the output of the following?

```
docker ps
docker logs <yacht container id>
```
Replace `<yacht container id>` with the id of the yacht container.

How have you installed docker?

**Comment by hibare** [comment]
Actually, I did not see anything in logs expect startup logs.

Docker installation through standard apt installation process

**Comment by hibare** [comment]
I'll give it a try once again some time tomorrow

**Comment by SelfhostedPro** [comment]
Try doing the official docker install from their repo. That's usually the best way. If you can send the startup logs that may provide some insight into the issue. Are you using a reverse proxy or anything?

**Comment by hibare** [comment]
No, nothing special. I was following steps listed on GitHub repo

**Comment by hibare** [comment]
I was trying to test the new version before using that one on my actual server

**Comment by hibare** [comment]
Latest image works
