### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by ShojinSpear** [SelfhostedPro/Yacht#221]
Hi,

First thanks for the greath project.

This is not really a issue. Is more a help request. 

I´m using Nginx proxymanager to act  reverse proxy for my internal apps without expose them directly, and I enable WEBPROXY on the admin

The problem is that I´m stuck on display the dasboard as I can´t make websocket work.

Do you have any idea.

Thanks.

**Comment by SelfhostedPro** [comment]
The best place to ask for help is the selfhostedpro discord: https://discord.gg/KpKutvC

For websockets to work you should just need to tick the websocket box in nginx proxy manager. I test this setup for every release so it should definitely be working.

**Comment by SelfhostedPro** [comment]
Have you made any progress on this?

**Comment by ShojinSpear** [comment]
Yes,

The problem is that I want to mount a folder on host to Yast to keep the config.

After a create a docker volume its work.

Right now is working .

Thanks.
