### ISSUE TITLE
How do you edit a container after it's created from a template?

### ISSUE THREAD

**Issue by poldim** [SelfhostedPro/Yacht#225]
So I created an application from a template, SWAG in my case.  I've got it up and running.  Now I want to modify some of the settings with which it's started.  How do I do this? 

Normally, I'd be using a docker-compose file.  I'd just make the changes and then recreate the container.  

I tried stopping the container to see if additional options become available, but didn't see anything.

**Comment by SelfhostedPro** [comment]
If you want to edit things you should use the yacht projects (docker-compose) for now. I'm working on enabling editing for containers.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by poldim** [comment]
> If you want to edit things you should use the yacht projects (docker-compose) for now. I'm working on enabling editing for containers.

Is there more info on yacht projects?  I see the docs dont mention much but they may not be update?

**Comment by SelfhostedPro** [comment]
Here's the documentation on docker-compose projects in yacht. https://yacht.sh/Advanced/docker-compose/

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by SelfhostedPro** [comment]
This is now available in the :devel tag of the container. It's very new and there's no confirmation dialogue yet so be careful with it.

**Comment by poldim** [comment]
thanks I'll try this out this week
