### ISSUE TITLE
Swarm Support

### ISSUE THREAD

**Issue by obsidiangroup** [SelfhostedPro/Yacht#226]
How does Yacht handle swarms?  Upon installing and launching Swarm, there seems to be no support for Swarms.  Is this the case, of if I replicate Yacht across the swarm, will all containers, networks, etc show up as in PortainerL

**Comment by SelfhostedPro** [comment]
No it doesn't. I won't be adding support for it either as it ads a lot of complexity.

**Comment by wickedyoda** [comment]
There is no support for swarms at this time, but there has been a couple minor changes. The last time we met about it, there was a new version in a different repo. A version 2.0 that was priority.
