### ISSUE TITLE
[Feature Request] custom template integration

### ISSUE THREAD

**Issue by alant54** [SelfhostedPro/Yacht#227]
Hello, I already want to say you that I love your project and hope a new release will coming soon... 
I have open an issue to ask you a new feature, an option for creating your own list of templates inside yacht.
For example, at the end of creating a new application add a button "create template" for saving all volume path / network port / environment variable / global option in a template and add him in the list of your choice.
Finally, after creating your own list a simple button to export in json your custom list of templates.
I think this feature can be really helpful for easily recreate our container and for the community who can create and share their own template list.
Let me know what you think about this idea...

**Comment by SelfhostedPro** [comment]
I'm working on a website for this here: https://github.com/SelfhostedPro/Yacht-Designer

**Comment by SelfhostedPro** [comment]
https://shipwright.yacht.sh is where this project lives. Not very refined but it's usable.
