### ISSUE TITLE
[Feature Request] Scheduled Tasks

### ISSUE THREAD

**Issue by yllekz** [SelfhostedPro/Yacht#247]
Hey there, I was wondering if it would be possible to roadmap a control panel to set up automated/scheduled tasks for containers. Things like starting/stopping them on schedules, pulling logs, checking for updates/etc. Portainer sort of has this feature but I feel it could be done a lot better. Thoughts?

**Comment by SelfhostedPro** [comment]
I could definitely look into setting something like this up. What are your thoughts on how you think it should be done?

Also, where in the UI do you think it would make sense to add it in?

**Comment by yllekz** [comment]
I'd imagine maybe it would fit in either as a setting in "Settings" or its own dedicated section in the sidebar.

I think the general idea could go something like this:
* Name of task
* Target container
* Date/time the job should run (YYYY-MM-DD HH:MM:SS)
* Trigger [options such as runs on a schedule, runs when a log is posted, etc.]
* --Frequency (Run once, or recurring?)
* --If recurring, recurrence schedule: [Run every x seconds/minutes/hours/days/weeks/months/etc]
* --"Stop task if it runs longer than x seconds/minutes/hours/days/weeks/months/etc"
* Action [Maybe a UI of Docker commands? as well as a box where you can just enter whatever command?]

**Comment by wickedyoda** [comment]
@yllekz Please comment back if this is still an issue or feature you would like someone to look into adding.

**Comment by yllekz** [comment]
I still think that would be a cool idea. Portainer claims to have this feature but doesn't really coherently convene it in the UI so there is definitely a need for an easier way to do it.

**Comment by wickedyoda** [comment]
Your talking about the Edge job features for portianer, it's still a beta project and from the looks of this page (https://docs.portainer.io/v/ce-2.11/user/edge/jobs), it's a web interface to schedule and use cron jobs within the OS. 

@SelfhostedPro Do you think this is something we could add to future planning for Yacht?
