### ISSUE TITLE
Template Variables reset

### ISSUE THREAD

**Issue by ml3456** [SelfhostedPro/Yacht#251]
Any idea why my template variables reset? Not a bad program was disappointed when setting up sonarr that the variables changed back to default.  Not sure why.  Does this have a backup program>

Thanks, ML

**Comment by SelfhostedPro** [comment]
The only reason they should reset is if you're not using persistent storage. You can back up templates and variables using the export/import button on the server info page in server settings.

**Comment by SelfhostedPro** [comment]
I'm going to go ahead and close this since I haven't heard back. If this happens again, feel free to tell me in this issue and I'll reopen it.
