### ISSUE TITLE
[BUG] 500 Internal server error on login page

### ISSUE THREAD

**Issue by JonasUJ** [SelfhostedPro/Yacht#26]
**Describe the bug**
The login page causes an internal server error

**To Reproduce**
1. Go to '/account/login'

**Expected behavior**
A login form

**Additional context**
Docker version 19.03.8
Running on windows with WSL 2 and powershell

**Logs**
```
...
File "/app/templates/account/login.html", line 2, in <module>
    {% import 'macros/form_macros.html' as f %}
File "/app/templates/layouts/base.html", line 40, in <module>
    {% block content %}
File "/app/templates/account/login.html", line 22, in <module>
    <a href="{{ url_for('account.reset_password_request') }}">Forgot password?</a>
...
werkzeug.routing.BuildError: Could not build url for endpoint 'account.reset_password_request'.
Did you mean 'account.reset_password' instead?
```

**Comment by joelrader-ping** [comment]
Having the same issue

**Comment by SelfhostedPro** [comment]
I'll take care of this in a few moments. This happened due to the resolution to another issue. Thanks!

**Comment by SelfhostedPro** [comment]
I am really curious to know how your experience goes using WSL 2. I haven't tested on it.
