### ISSUE TITLE
[Feature Request] Deploy multiple containers from a single file

### ISSUE THREAD

**Issue by Hukuma1** [SelfhostedPro/Yacht#260]
Hi. Jumped over from Portainer to check this out and so far it's already pretty awesome. Keep up the great work.

I am trying to figure out a way to export all of my settings to a docker-compose of the 15+ containers I'm running now. And then spin up all those containers and their environment settings on another machine. Is there a way to do this? One giant docker-compose file? 15 different docker compose files? Basically something like the template json file you list as an example under templates. Except I want to install all of the apps I'd list in one go.

I'm not looking at backing up the config folders in each or any data, just the initial startup env settings, etc. I couldn't easily find this function in Portainer (is it Stacks?) so I figured I'd ask here.

**Comment by SelfhostedPro** [comment]
You would definitely want to do this via docker-compose. You can do this in Yacht via the projects section. I'm working on a version 0.0.6-alpha with a built in editor for docker-compose (you can add `:devel` to the end of `selfhostedpro/yacht` when deploying yacht to get this until it's released in the latest image.

There's not a tool for exporting this info from running containers as far as I know. It may be a good idea to separate your applications by type into different docker-compose projects. If you want someone to talk to about this, feel free to pm me here: https://discord.gg/KpKutvC

**Comment by SelfhostedPro** [comment]
Docker-compose support is now in the latest image. Going to close this. If you have any questions about this feel free to ask me here and I'll re-open.
