### ISSUE TITLE
Misleading "Add New Apps" button sub header

### ISSUE THREAD

**Issue by JonasUJ** [SelfhostedPro/Yacht#27]
On /apps the "Add New Apps" button has a sub header that says "Invites a new user to create their own account", but i believe something like "Add an app using an existing template" would be more appropriate.

**Comment by SelfhostedPro** [comment]
Ah, leftover from some code that the boilerplate uses. I'll get that fixed. Thank you! You'll be able to add an app not from a template soon. I'm just sorting out the final bits of the form.
