### ISSUE TITLE
BitwardenRS Data directory not populating at setup

### ISSUE THREAD

**Issue by laoistom** [SelfhostedPro/Yacht#283]
Hi Guys, 

First time to post an issue to Github, be gentle with me. 

I noticed an issue where if I deploy BitwardenRS and Watchtower using Yacht, Bitwarden doesn't required a path for the /data directory and defaults to the docker default volume. However when Watchtower detects an update and then performs the update it does so with a newly generated Docker Volume. 

I ran into this when Watchtower updated my Bitwarden deployment on the 7th of February. 

My suggested fix is to have yacht define a Data volume at deployment to ensure data persistence. 

I understand that this can be done by the user during deployment but I feel it would be a far better user experience if this was automatic at point of deployment. 

Thanks
 
Tom

**Comment by SelfhostedPro** [comment]
Hey, the fact that the bind mount was removed sounds like a watchtower issue as that's the only thing that would have done that. A container cannot change that on its own. 

Docker will automatically use a volume for defined paths in a container if you don't bind mount them as long as it's defined in the dockerfile so there's nothing that yacht could change at that point. 

Yacht includes functionality to update containers. If you wanted to avoid automatic updates you could just use the check for updates button in the app list and then it's a simple click to update from there (it uses watchtower on the backend to do the update with the `--run-once` and `--cleanup` flags targeting the container you're updating).

**Comment by laoistom** [comment]
Perfect thanks for that. I'll disable watchtower and use that feature in yacht.

**Comment by SelfhostedPro** [comment]
Glad to hear it. It may still be a good idea to open an issue in the watchtower repo so they know about it.
