### ISSUE TITLE
Theme colors resetting after user timeout.

### ISSUE THREAD

**Issue by alexandzors** [SelfhostedPro/Yacht#299]
App version: **v0.0.6-alpha-2021-02-19--20**

Steps to reproduce:
1. Deploy Yacht via docker-compose using example in docs.
2. Login and go to settings > themes
3. Change primary and secondary colors
4. Wait for user session timeout?
5. Reload for login page
6. Login
7. Theme colors set in step 3 are now back to default colors but theme options still shows ones set by user.

**Comment by SelfhostedPro** [comment]
Can you confirm if this is happening in the release as well?

**Comment by marcjmiller** [comment]
I've noticed this too,I didn't tie it specifically to timeout but I've noticed them going back to default what I felt like was sporadically. I'll pay more attention to this to try and get more feedback.

**Comment by alexandzors** [comment]
Looks like with the new update its still resetting the theme on session timeout. Relogging and restarting yacht doesn't fix it.

**Comment by alexandzors** [comment]
Just tested it on `:devel` and it seems to be fixed.

**Comment by SelfhostedPro** [comment]
Glad to hear it. I'll close this once it's merged into latest.
