### ISSUE TITLE
Yacht Page doesn't load on trying to install calibre-web

### ISSUE THREAD

**Issue by jdainen** [SelfhostedPro/Yacht#30]
I went to apps.
Add calibre-web
Change the host path for books and config.

It doesn't download the image
and hangs on the following page.
http://192.168.8.183:5000/apps/add/11/info
"This page not working"

From modest _wu:
[2020-06-26 15:50:35 +0000] [252] [CRITICAL] WORKER TIMEOUT (pid:285)
[2020-06-26 15:50:35 +0000] [285] [INFO] Worker exiting (pid: 285)
valid
['PUID=1000', 'PGID=100']
{'8083': '8083/tcp'}
stop
[2020-06-26 15:50:35 +0000] [286] [INFO] Booting worker with pid: 286
RaygunProvider error: ApiKey not set, errors will not be transmitted

**Comment by SelfhostedPro** [comment]
Those logs aren't related to it not showing. Are there any other errors?

**Comment by jdainen** [comment]
That's it.  Nothing else showed.

**Comment by jdainen** [comment]
The log is from Yacht.  After trying to load calibre-web.

**Comment by SelfhostedPro** [comment]
Can you pull the latest image and try again?

**Comment by SelfhostedPro** [comment]
Any updates?

**Comment by SelfhostedPro** [comment]
Closing because this is stale. If this happens again please let me know and I'll reopen.
