### ISSUE TITLE
Yacht is changing permissions of compose folder

### ISSUE THREAD

**Issue by eloo** [SelfhostedPro/Yacht#305]
Hi,

i just tested the new version with the compose editing and for this i have mounted my compose folder into yacht and then all my file permissions have been overwritten by yacht to 911 as owner.

I'm not sure why this is done by yacht but its going to cause problems when you have config folders inside. 
So yacht should really do NOT change permissions and ownerships of mounted folders without any reason.

Maybe the reason for the permission change is because compose is mounted per default under /config/compose? 

Thanks

**Comment by SelfhostedPro** [comment]
Ah, the startup script is recursive: https://github.com/SelfhostedPro/Yacht/blob/master/root/etc/cont-init.d/30-config

I'll get that changed in the next hotfix. In the meantime mount `/compose` instead and set the `COMPOSE_DIR` environment variable to `/config` when running yacht. (`-e COMPOSE_DIR=/compose`

**Comment by eloo** [comment]
Yep have just tested it.. same result :(

**Comment by SelfhostedPro** [comment]
Had a typo. Did you set COMPOSE_DIR to /compose or /config?

Did you change permissions back to how they were previously when testing that? I'll check and see if permissions are set anywhere else.

**Comment by eloo** [comment]
i mostly looks like this
```
volumes:
      - ./config:/config
      - /home/user/docker:/config/compose
      - /var/run/docker.sock:/var/run/docker.sock
    image: selfhostedpro/yacht
    environment:
      - COMPOSE_DIR=/compose

**Comment by SelfhostedPro** [comment]
Change the `/home/user/docker:/config/compose` to `/home/user/docker:/compose` and that should fix it.

**Comment by SelfhostedPro** [comment]
The config directory has it contents` permissions set recursively so moving the compose stuff outside of `/config` should fix this.

**Comment by eloo** [comment]
ah yeah. now its working..

maybe you should update your example and the default value for the COMPOSE_DIR.

Thanks for the very very quick response.

**Comment by SelfhostedPro** [comment]
I definitely will. Just need to get the permissions command sorted for startup. I'll pin this issue in the meantime.

**Comment by SelfhostedPro** [comment]
Fix is now building for the :devel tag. Once this is done it should be good to go:

https://github.com/SelfhostedPro/Yacht/actions/runs/589410729

**Comment by SelfhostedPro** [comment]
New version is released with this fix. Thanks again for reporting this!
