### ISSUE TITLE
Template Variables Not Filled on Application Creation

### ISSUE THREAD

**Issue by ZachMyers3** [SelfhostedPro/Yacht#310]
I can see template variables getting filled in the other fields, but not in my labels from the template. Screenshot below.

![image](https://user-images.githubusercontent.com/7140882/108752112-0f81f100-7511-11eb-8cbd-344f187118a9.png)

![image](https://user-images.githubusercontent.com/7140882/108752186-245e8480-7511-11eb-9752-7c28f44ea03a.png)

**Comment by SelfhostedPro** [comment]
Template variables don't affect labels yet. I'll definitely be getting this into the next hotfix (0.0.6-hf2).

**Comment by ZachMyers3** [comment]
Can you point me at a couple files I could look at to maybe try this? Funnily enough I'm familiar with both fastapi and vue so I think I could get up to speed on this project relatively quickly to help contribute.

**Comment by SelfhostedPro** [comment]
That would be awesome!

You would want to take the t_var stuff from [this](https://github.com/SelfhostedPro/Yacht/blob/127cabdf42a6d2c1407b5db775e49d80854f2f59/backend/api/utils/apps.py#L66) function and copy it over to [this](https://github.com/SelfhostedPro/Yacht/blob/127cabdf42a6d2c1407b5db775e49d80854f2f59/backend/api/utils/apps.py#L134) one. 

Let me know if you have any trouble getting the develop environment set up. I made some changes that haven't need added to the [development instructions](https://yacht.sh/Developer_Information/DeveloperSetup/) yet. I can also walk you through in [discord](https://discord.gg/KpKutvC) or on slack if you're looking for something more realtime.

**Comment by ZachMyers3** [comment]
Done in !319
