### ISSUE TITLE
[Feature Request] Adjust Dashboard View to Improve Performance Impact

### ISSUE THREAD

**Issue by ZachMyers3** [SelfhostedPro/Yacht#311]
I personally cannot load the dashboard page, as I have enough containers that it causes a lock up.

Potentially paginating this page or optionally loading the CPU performance graphs via a dropdown would improve this.

**Comment by SelfhostedPro** [comment]
How many containers are you using? Up to 100 have been verified as working. I'm looking into alternative methods of displaying this to improve performance.

**Comment by ZachMyers3** [comment]
I "only" have 57 containers running but I do experience a hard lock if I stay on the dashboard too long.

**Comment by ZachMyers3** [comment]
Worth mentioning, I tested on chrome and it really does run painlessly on my setup, Firefox appears to be causing the issue.

**Comment by SelfhostedPro** [comment]
Once this is done can you try this to see if it's more performant? 

https://github.com/SelfhostedPro/Yacht/actions/runs/590209397

It'll be in the devel tag. I swapped out chartjs on that page for the standard progress bars from vuetify.

**Comment by ZachMyers3** [comment]
I'm no longer getting a hard lock from the tab but it's still pretty resource intensive.

**Comment by SelfhostedPro** [comment]
Once this is done stats will only update if they've changed: 
https://github.com/SelfhostedPro/Yacht/actions/runs/590711090

I'm going to work on doing the conversion to mb on the backend so it's less work for your browser to do as well and it will reduce the number websocket messages that need to be sent.

**Comment by SelfhostedPro** [comment]
This is the performance difference between latest and devel currently:
![image](https://user-images.githubusercontent.com/66331933/108781961-98078e00-751f-11eb-8a3a-155569900b04.png)
I'll do another measurement once my other optimizations are done and let you know. Currently it's about 73% better as far as cpu usage goes.

**Comment by ZachMyers3** [comment]
It's definitely better! For whatever reason Chrome is grossly better optimized on the dashboard as compared to Firefox as well.
