### ISSUE TITLE
Icon and other menu not displaying properly in offline mode

### ISSUE THREAD

**Issue by SysAdmin74** [SelfhostedPro/Yacht#317]
When I move the server to offline mode, noticed that the icon do not load and the page took a long time to load up in the browser.
I wonder could it be cause of this `https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.min.css` cannot load during offline.

Forgive me if I make a mistake here. First time reporting issues

**Comment by SelfhostedPro** [comment]
No worries! This is the right place to report this. I'll take a look and see if there's a good way to get those available offline.

**Comment by SysAdmin74** [comment]
Cool, my current solution was have cached data on server to keep those temporary available in offline

**Comment by SelfhostedPro** [comment]
Just wanted to see if this is still there. I believe I manually downloaded those into the repo.
