### ISSUE TITLE
[Bug Report] Logs overlap making them unreadable

### ISSUE THREAD

**Issue by jeffr1975** [SelfhostedPro/Yacht#323]
Container Logs in Yacht web interface seem to overlap making them unreadable. I am using the latest docker container for Yacht as of today.  If I highlight the text, I can make out the highlighted test.

I tired a Chromebook,  Chrome on Windows and Edge on Windows.

**Comment by SelfhostedPro** [comment]
Can you provide the exact version? Should be located at the bottom of the settings page.

**Comment by SelfhostedPro** [comment]
I only ask because it's working fine for me using both firefox and chrome

![image](https://user-images.githubusercontent.com/66331933/109354449-b082eb80-7832-11eb-84fa-77850f13a358.png)

Also, can you check in the console log of your browser for any errors?

**Comment by jeffr1975** [comment]
Thanks for responding.  I am loving this over portainer for how I use it.

Version: v0.0.6-alpha-2021-02-25--15

Console errors.  I am accessing Yacht using the IP of my Windows computer that runs Docker.  Sorry if I am doing something silly.

Failed to load resource: the server responded with a status of 401 (Unauthorized)
Home.vue:91 WebSocket connection to 'ws://192.168.50.125:8000/api/apps/stats' failed: 
readAppStats @ Home.vue:91
:8000/api/auth/me:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
:8000/api/auth/refresh:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
auth.js:87 Error: Request failed with status code 401
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:62)
Home.vue:147 WebSocket is already in CLOSING or CLOSED state.
closeStats @ Home.vue:147
:8000/api/auth/refresh:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
auth.js:87 Error: Request failed with status code 401
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:62)
:8000/api/auth/me:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
vue.runtime.esm.js:1888 TypeError: Cannot read property 'name' of undefined
    at a.ze (ApplicationDetails.vue?924c:1)
    at a.e._render (vue.runtime.esm.js:3548)
    at a.i (vue.runtime.esm.js:4066)
    at ni.get (vue.runtime.esm.js:4479)
    at new ni (vue.runtime.esm.js:4468)
    at On (vue.runtime.esm.js:4073)
    at a.xi.$mount (vue.runtime.esm.js:8415)
    at init (vue.runtime.esm.js:3118)
    at n (vue.runtime.esm.js:3301)
    at m (vue.runtime.esm.js:5978)
rt @ vue.runtime.esm.js:1888

**Comment by SelfhostedPro** [comment]
Try refreshing the page with control+shift+r and it should redirect you to the login page. It looks like it timed out. I've been working on getting that process to work better but progress has been slow.

**Comment by jeffr1975** [comment]
There are less errors with Ctrl+Shift_R.  But logs are still unreadable.  Just this error.

vue.runtime.esm.js:1888 TypeError: Cannot read property 'name' of undefined
    at a.ze (ApplicationDetails.vue?924c:1)
    at a.e._render (vue.runtime.esm.js:3548)
    at a.i (vue.runtime.esm.js:4066)
    at ni.get (vue.runtime.esm.js:4479)
    at new ni (vue.runtime.esm.js:4468)
    at On (vue.runtime.esm.js:4073)
    at a.xi.$mount (vue.runtime.esm.js:8415)
    at init (vue.runtime.esm.js:3118)
    at n (vue.runtime.esm.js:3301)
    at m (vue.runtime.esm.js:5978)
rt @ vue.runtime.esm.js:1888

**Comment by SelfhostedPro** [comment]
Hmmm. That shouldn't impact the log rendering. Can you send me a screenshot? I had an issue where the logs were using a list item instead of plain text on accident and it was adding bulletpoints. Could you try the :devel tag and see if it's working as expected now?

**Comment by jeffr1975** [comment]
Screenshot with Version: devel-2021-02-26--21
It looks the same with all 6 of my containers and on all browsers I try.

![Screenshot 2021-02-26 4 39 11 PM](https://user-images.githubusercontent.com/79524510/109362791-60ffe800-7851-11eb-9d30-2d61e7dee6b0.png)

vue.runtime.esm.js:1888 TypeError: Cannot read property 'name' of undefined
    at a.ze (ApplicationDetails.vue?cb9e:1)
    at a.e._render (vue.runtime.esm.js:3548)
    at a.i (vue.runtime.esm.js:4066)
    at ni.get (vue.runtime.esm.js:4479)
    at new ni (vue.runtime.esm.js:4468)
    at On (vue.runtime.esm.js:4073)
    at a.xi.$mount (vue.runtime.esm.js:8415)
    at init (vue.runtime.esm.js:3118)
    at n (vue.runtime.esm.js:3301)
    at m (vue.runtime.esm.js:5978)
rt @ vue.runtime.esm.js:1888

**Comment by SelfhostedPro** [comment]
Can you try running in firefox to see if the issue persists? It's definitely a rendering issue on the frontend but I can't seem to recreate it.

**Comment by jeffr1975** [comment]
docker run -d \
    --name=firefox \
    -p 5800:5800 \
    --shm-size 2g \
    jlesage/firefox

![Screenshot 2021-02-26 5 05 28 PM](https://user-images.githubusercontent.com/79524510/109364697-f81a6f00-7854-11eb-804d-c21d92eea65a.png)

**Comment by jeffr1975** [comment]
It has to be something with my compose or that I am using docker on Windows?
Here is my compose.  Notice the docker.sock.  It has two leading forward slashes: "//var", which I got from this link.  I am not sure if that is relevant.  Everything else works like the CPU an Memory on the Yacht Dashboard.

https://stackoverflow.com/questions/36765138/bind-to-docker-socket-on-windows

version: '3.7'
services:
    yacht:
        container_name: yacht
        volumes:
            - '//var/run/docker.sock:/var/run/docker.sock'
            - '/run/desktop/mnt/host/c/Docker/Volumes/Yacht:/config'
        ports:
            - '8000:8000'
        image: 'selfhostedpro/yacht:devel'
        restart: always
        stdin_open: true
        tty: true

**Comment by jeffr1975** [comment]
OK, it was one of these.

stdin_open: true
tty: true

I add these to Minecraft so I can see real time output when running docker exec.  After removing those I can see the logs!

**Comment by SelfhostedPro** [comment]
Ah, interesting. I guess I should have asked to see the docker-compose first. Thanks!
