### ISSUE TITLE
[Feature Request] Option to use URL Override for generated links in Yacht Apps 

### ISSUE THREAD

**Issue by marcjmiller** [SelfhostedPro/Yacht#325]
**Is your feature request related to a problem? Please describe.**
When using Yacht behind a reverse proxy (via Nginx Proxy Manager) to access yacht via `yacht.example.com`, all of my services link to `yacht.example.com:<port>`, which doesn't work with my current configuration.

**Describe the solution you'd like**
It would be nice to have a switch in the config to have links to use an URL substitution, like a HOST_URL_OVERRIDE that when set, overrides the URL for App links to `<HOST_URL_OVERRIDE>:<port>`.

**Describe alternatives you've considered**
Currently I'm using a redirection host vs proxy host which relieves the issue, and I could probably do a custom configuration for the proxy host, but I don't know nginx or Nginx Proxy Manager well yet.

**Additional context**
That's all, from my usage so far, Yacht is amazing, thanks for all your hard work!

**Comment by SelfhostedPro** [comment]
Would it be better for me to add this as an option to the deploy form? That way if you have multiple domains you can set them without needing a second yacht instance.

**Comment by marcjmiller** [comment]
Yeah, that would be amazing.  Currently I'm only using one domain so it didn't cross my mind, but I could picture hardcore home-labbers wanting something like this.  In my case, I'm mostly wanting an option for links to go from `yacht.example.com:<port>` to `<host_ip_address>:<port>` because all of my services are on the same host.  I have NPM setup for my other services as an example `radarr.example.com` is mapped to `<host_ip_address>:7878` so the problem comes in with the current `yacht.example.com` radarr WebUI link mapping to `<host_ip_address>:8000:7878` which doesn't work.

**Comment by SelfhostedPro** [comment]
I'll take a look at adding this in shortly. I'm currently rebuilding the app detail page so it'll probably show up there first.

**Comment by marcjmiller** [comment]
Thanks for the super speedy response, it is pretty low-threat for me since the redirect host works, it just isn't as pretty. :)
