### ISSUE TITLE
[Bug Report] Tabs getting 'smooshed' in App Info pages

### ISSUE THREAD

**Issue by marcjmiller** [SelfhostedPro/Yacht#326]
**Describe the bug**
Currently, I've noticed (at 1080p and 1440p at least), on the App Info page (`http://<YACHT_ADDRESS>/#/apps/<APP_NAME>/info`) the tabs fall behind the main UI element and are smooshed a little, as seen by the highlight here cutting off the bottom including the slider showing the selected tab.

**To Reproduce**
1. Go to the Dashboard
2. Click on Applications
3. Click on any application you currently have deployed
4. Tabs are missing the bottom 20 pixels or so

**Expected behavior**
I expected (and the docs show) a bit of bottom spacing and an underline that I can't see in Chrome/Firefox/Edge.  IE surprisingly shows the underline and space, but doesn't highlight correctly or grab colors.

**Screenshots**
The container that is highlighting has some space on the bottom being hidden, as seen here: 
![image](https://user-images.githubusercontent.com/48929970/109400501-15b00d00-7917-11eb-976d-78b6965b0ac5.png) ![image](https://user-images.githubusercontent.com/48929970/109400582-91aa5500-7917-11eb-928b-6fce8507e208.png)

I also took a quick screen recording gif that shows a little stutter where the content moves upward a bit as well.
![Screen Recording](https://user-images.githubusercontent.com/48929970/109405463-ba921080-793e-11eb-974b-50fe1ec04d4b.gif)

IE is extra special: 
![image](https://user-images.githubusercontent.com/48929970/109405579-f11c5b00-793f-11eb-974a-1db04b67d3b5.png)

**Desktop (please complete the following information):**
 - OS: Win10 Pro
 - Browser: Chrome 88.0.4324.190/Firefox 86.0 (64-bit)/Edge 88.0.705.81
 - Yacht Version: v0.0.6-alpha-2021-02-19--20

**Additional context**
Installed yacht per the [official docs](https://yacht.sh/Installation/yacht/) to a Debian VM under Proxmox.

** Logs **
Nothing looks out of the ordinary in the browser console or docker log.

**Comment by marcjmiller** [comment]
As a note, I'm able to fix the page by changing `d-flex` to the div immediately following the tab bar.  

Screenshot:
![image](https://user-images.githubusercontent.com/48929970/109406122-80c40880-7944-11eb-926e-83a8c9f4f364.png)

**Comment by marcjmiller** [comment]
https://github.com/SelfhostedPro/Yacht/blob/ed92e1bb4528e06117b8a9023087bb81ee2f041e/frontend/src/components/applications/ApplicationDetails.vue#L5

For some reason I can't install the packages to test locally after forking the project so I could submit a PR, but it appears this is the line that would get `d-flex` to fix the glitch.

**Comment by SelfhostedPro** [comment]
Here's the info to setup a dev environment: https://yacht.sh/Developer_Information/DeveloperSetup/

I'll make the change in the morning and upload to the :devel tag if you're not able to sort it out but I'd prefer if you could get credit for helping fix this.
