### ISSUE TITLE
[Bug Report] Usernames at login are case SeNsItIvE

### ISSUE THREAD

**Issue by marcjmiller** [SelfhostedPro/Yacht#328]
**Describe the bug**
Usernames are case sensitive for login, but typically this is not the case.  Major examples would be Google/Facebook/Twitter/Instagram.

**To Reproduce**
1. Go to Login page on a fresh install.
2. Set your username to `AdMiN@yacht.local` and enter the default password.
3. Click Login or Press enter.
4. Get `Bad Request: Invalid Username or Password`.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: All
 - Yacht Version: develop branch

**Additional context**
Will be submitting a PR momentarily to fix, tested locally against Develop.  :smile:

**Comment by SelfhostedPro** [comment]
Thanks! I'll take a look at this in a few and merge.
