### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by SelfhostedPro** [SelfhostedPro/Yacht#345]
- [ ] Header
- [ ] AppBar
- [x] Nav - Side Bar
- [x] Nav - Bottom Bar (for mobile)
- [x] Router
- [ ] Tabbed nav within Resources
- [ ] Tabbed nav within Applications
- [ ] Tabbed nav within Deploy (Mobile)

**Comment by marcjmiller** [comment]
Edited to add the Header, even though I somehow broke the markdown to add a space.

**Comment by marcjmiller** [comment]
Sidenav looking pretty done after #353 , marking as such. :)
![sidenav](https://user-images.githubusercontent.com/48929970/111041914-9fc49f00-8408-11eb-896e-c7adecf44590.gif)

**Comment by marcjmiller** [comment]
Fixed bottom/sidebars to a point where there isn't much to be done with them, marking them complete.
![yacht_desktop_updated](https://user-images.githubusercontent.com/48929970/111087836-391fae00-84fa-11eb-8316-5926aac96d31.gif)
![yacht_mobile_updated](https://user-images.githubusercontent.com/48929970/111087837-391fae00-84fa-11eb-807e-5c9977669594.gif)
