### ISSUE TITLE
[Feature Request] Ability to bind ports for local IP

### ISSUE THREAD

**Issue by tvasenin** [SelfhostedPro/Yacht#359]
I want to be able to specify local binding for port mapping during deployment, like:
```
"WebUI" : "127.0.0.1:9091:9091/tcp"
```

**Comment by SelfhostedPro** [comment]
Should this be a toggle to bind to localhost or should IP be another field in the ports section?

**Comment by tvasenin** [comment]
For my setup, any of these two options will do, but I'd say it would be better to be able to specify any valid binding.
