### ISSUE TITLE
[Bug Report] Not all apps are showing up in dashboards

### ISSUE THREAD

**Issue by SelfhostedPro** [SelfhostedPro/Yacht#387]
Some users are limited to 6 containers showing in the dashboard. At this point I'm thinking it could be related to http2 support with the current nginx config but that would even be limited to 10 from what I've read on browser compatibility. 

No logs indicate an issue, the requests just time out.

**Comment by mdorchain** [comment]
The endpoint is returning all the containers in the response, but the containers are not rendered.
In the same way, on a manual refresh the endpoint still returns all the objects but they are not rendered.
I could reproduce the same behavior on Edge and Firefox.
I attached some screenshots of the first load and refresh.

![dashboard-Screenshot 2021-04-24 233110](https://user-images.githubusercontent.com/11390079/115964431-13ed7900-a557-11eb-89ae-c918602f9326.png)
![dashboard-refresh-Screenshot 2021-04-24 233146](https://user-images.githubusercontent.com/11390079/115964432-151ea600-a557-11eb-9d90-8bcc63d05536.png)

**Comment by SelfhostedPro** [comment]
I'm modifying the Frontend and backend so only 1 request is needed. This should resolve this issue as I believe it's a limit with server sent events.

**Comment by LongDono** [comment]
Thanks. Let me know when you need any testing. The default for some configuration items is 5, perhaps those not experiencing this issue have a higher value.

"max-concurrent-uploads": 5

**Comment by SelfhostedPro** [comment]
This is currently building as a result of #400. Once this is done it will be available for testing on the :devel tag. https://github.com/SelfhostedPro/Yacht/actions/runs/883796431

**Comment by SelfhostedPro** [comment]
Fix has been published to the latest release. If there are any issues with it, comment here and I'll reopen.

**Comment by LongDono** [comment]
Just upgraded, works properly. Unfortunate it did not work out the way you had planned. Thanks for your efforts. ❤️

**Comment by mdorchain** [comment]
All containers are now showing. Mem usage is updating but not the CPU. 
I guess you already mentioned it in #408 .
I also noticed some errors in the console, this could be related.

![image](https://user-images.githubusercontent.com/11390079/120344103-dcc77000-c32b-11eb-833b-cc982120841f.png)

**Comment by SelfhostedPro** [comment]
> All containers are now showing. Mem usage is updating but not the CPU.
> I guess you already mentioned it in #408 .
> I also noticed some errors in the console, this could be related.
> 
> ![image](https://user-images.githubusercontent.com/11390079/120344103-dcc77000-c32b-11eb-833b-cc982120841f.png)

Can you post your logs? CPU not working on that post is likely related to the hardware they’re running on. CPU and ram should be working. Make sure to clear your cache as well as that may resolve the console errors after the update.
