### ISSUE TITLE
[Feature Request] Ability to login to a private registry

### ISSUE THREAD

**Issue by kirkleon** [SelfhostedPro/Yacht#389]
**Is your feature request related to a problem? Please describe.**
I run a private docker registry as part of my home set up where I push some custom images, and currently Yacht cannot pull from there because it is not logged into the registry. I don't _think_ there's any way to do that in the current set up but I'd love to see that feature added!

**Describe the solution you'd like**
Whatever allows me to set credentials and have Yacht do a `docker login`/`dclient.login` equivalent before pulling. Environment variables on the yacht container would be fine.

**Describe alternatives you've considered**
I did fiddle with getting into the container and trying a `docker login`, but apparently the python docker library requires the manual `client.login` call. Right now I just SSH into the host box and do a manual pull when I need to update the private images.

**Additional context**
No other context, just wanna say this project is really impressive and I already like it a lot! Sorry if this is already supported and I just couldn't find it.

**Comment by SelfhostedPro** [comment]
Does it work if you use `docker login` inside the yacht container (don't know if you were doing it inside the container or on the host). I'll take a look at getting this setup. Why type of private registry are you using? I will need to set one up for testing.

**Comment by kirkleon** [comment]
Yeah I was doing it inside the yacht container. Had to actually `apk add docker` in it first, and it let me log in and I could pull from the actual docker command without a problem, but the python library didn't pick it up.

I'm just using the normal [`registry`](https://hub.docker.com/_/registry/) image for mine. Full disclosure it's been a while since I've set this up so I don't fully remember everything I did, but I seem to recall it being fairly easy to spin up. 

I'll throw in my (slightly modified) compose file but I don't think you need half of these if you don't care about "good" auth, the basic stuff might be enough for testing.

```docker-compose
version: "2.0"

services:
  registry:
    image: registry:2
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    ports:
      - "5000:5000"
    volumes:
      - "./registry/auth:/auth"
      - "./registry/data:/var/lib/registry"
    restart: unless-stopped
```

**Comment by SelfhostedPro** [comment]
Awesome, Thanks! I'll let you know when it's in devel and ready for testing.
