### ISSUE TITLE
[Bug Report] Blank page when loading projects using a .env file

### ISSUE THREAD

**Issue by TheAnachronism** [SelfhostedPro/Yacht#391]
1. Create a project in which the docker-compose.yml has a reference on a .env file
2. Create the .env file on the filesystem

**Expected behavior**
Project gets shown like any other one.

**Screenshots**
![image](https://user-images.githubusercontent.com/32616088/116069975-4fd62a80-a68c-11eb-9878-974a51874a3a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Yacht Version: newest docker image

** Logs **
``` 
vue.runtime.esm.js:1888 TypeError: t.project.services[e].env_file.join is not a function
    at ProjectDetails.vue?66a1:33
    at a.Bt [as _l] (vue.runtime.esm.js:2630)
    at a.Wa (ProjectDetails.vue?66a1:5)
    at a._render (vue.runtime.esm.js:3548)
    at a.i (vue.runtime.esm.js:4066)
    at ni.get (vue.runtime.esm.js:4479)
    at ni.run (vue.runtime.esm.js:4554)
    at Jn (vue.runtime.esm.js:4310)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at ct (vue.runtime.esm.js:1906)

TypeError: t.project.services[e].env_file.join is not a function
    at ProjectDetails.vue?66a1:33
    at a.Bt [as _l] (vue.runtime.esm.js:2630)
    at a.Wa (ProjectDetails.vue?66a1:5)
    at a._render (vue.runtime.esm.js:3548)
    at a.i (vue.runtime.esm.js:4066)
    at ni.get (vue.runtime.esm.js:4479)
    at ni.run (vue.runtime.esm.js:4554)
    at Jn (vue.runtime.esm.js:4310)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at ct (vue.runtime.esm.js:1906)
```

**Comment by SelfhostedPro** [comment]
Interesting. Is there anything on the backend as far as errors or just frontend? Should be an easy fix if it's just the Frontend.

**Comment by TheAnachronism** [comment]
I'll have a look but I didn't notice anything

**Comment by TheAnachronism** [comment]
Also how is the support for .env files? As far as I can see currently you can only create the docker-compose file itself for projects.

**Comment by SelfhostedPro** [comment]
You can't edit them in the UI but if you have an env file in the project directory it should be picked up by docker-compose.

**Comment by TheAnachronism** [comment]
It does but I was wondering if that was somewhere on the roadmap?
Because for basic projects a simple docker-compose might be enough but for larger ones it might be useful to have some sort of file explorer for something to add / edit configuration files and such.

**Comment by SelfhostedPro** [comment]
I may look into that but I feel like there are file browser projects out there that offer that ability better than I might be able to and for now I'd recommend going that path. 

In the future I may look into expanding the editor functionality. For now I'm really working on squashing bugs rather than adding features to get to a non-alpha version and be able to recommend Yacht for production use. 

Once I can get there I'll be adding a roadmap for features users want. Can you open up another issue about the file browser feature so I can leave that open once this is fixed?

**Comment by TheAnachronism** [comment]
Sure
#392

**Comment by nikosgpet** [comment]
I just came across the same error.

I found that the documentation about advanced projects was a bit difficult to understand so I proposed a few changes with a [Pull request](https://github.com/SelfhostedPro/Yacht-Docs/pull/5).

Kudos for Yacht, it's an awesome tool!

**Comment by SelfhostedPro** [comment]
Thank you! I’ll take a look and merge it when I can. I’m going on a road trip this week so it may not be until next week but I’ll merge it if I get some downtime. Super appreciated!

**Comment by SelfhostedPro** [comment]
Fix is building now. Should be testable on the :devel branch in an hour or so.

**Comment by SelfhostedPro** [comment]
Fix has been published to the latest release. If there are any issues with it, comment here and I'll reopen.
