### ISSUE TITLE
[Feature Request] Add forum

### ISSUE THREAD

**Issue by yajo** [SelfhostedPro/Yacht#395]
**Is your feature request related to a problem? Please describe.**
Yes, just want to talk with this community without becoming too serious about opening a new issue.

**Describe the solution you'd like**
https://docs.github.com/en/discussions should be enabled in the repo, so we have a place to discuss.

**Describe alternatives you've considered**
I see a discord channel, but I kinda prefer asynchronous communication sometimes. Also... well, for self-hosted pros, Discord is like a slap. At least, it could be [bridged to Matrix](https://t2bot.io/discord/).

**Comment by SelfhostedPro** [comment]
Hey, I’ll definitely be adding GitHub discussions once they’re available. They currently aren’t supported for individual owned repositories unless that’s changed recently. I am also looking into changing selfhostedpro into an organization but haven’t gotten far with that. I’ll leave this open for further discussion and any suggestions from the community.

**Comment by ptr1337** [comment]
@SelfhostedPro 
i can offer you to host a forum. Just hit me up in Discord:  ptr1337#0223

regards
