### ISSUE TITLE
[Bug Report] Support --user in template

### ISSUE THREAD

**Issue by yajo** [SelfhostedPro/Yacht#396]
**Is your feature request related to a problem? Please describe.**
Trying to set up my own templates.

Docker supports setting `--user` directly. LinuxServer images do their own trick using some variables, but for other normal images, setting the user there directly is easier.

**Describe the solution you'd like**
Templates should let me define the user, and be passed to the docker daemon.

**Describe alternatives you've considered**
Using docker-compose directly.

**Comment by SelfhostedPro** [comment]
https://docker-py.readthedocs.io/en/stable/containers.html

It doesn’t look like it would be too difficult to add this in. Should I add the group_add directive as well? Good catch, I didn’t even know this was a thing since I mainly stick to the lsio containers.

**Comment by Yajo** [comment]
> Should I add the group_add directive as well?

Not sure... from CLI `-u` is enough, but I don't know from API.
