### ISSUE TITLE
[Bug Report] GUI sliding animation when going back is the same as going forward = confusing

### ISSUE THREAD

**Issue by gleniat** [SelfhostedPro/Yacht#398]
**Describe the bug**
While navigaing back (Back button in the browser) new pages slide from the right side of the screen. It is confusing, because it seems like going forward.

**To Reproduce**
1. Click Back in your browser

**Expected behavior**
Going back will trigger new page sliding from left.

**Comment by SelfhostedPro** [comment]
This may be a limitation of how transition groups work in Vue.  I'll take a look when I have some time (hopefully this week).
