### ISSUE TITLE
[Bug Report] yacht did not respond, website gui did not respond

### ISSUE THREAD

**Issue by SkalCore** [SelfhostedPro/Yacht#408]
**Describe the bug**
yacht did not respond, website gui did not respond, process uvicorn generate high CPU Usage on Qnap NAS

**To Reproduce**
using yacht , after strarting yacht via Docker on qnap Nas Process uvicorn generate high CPU usage
Restarting container did not help. Start/Stop Container did not help

**Expected behavior**
using Yacht normal to control differnt docker container, website GUi for yacht did not respond, using Firefox last version, nothing changed in settings on yacht

**Screenshots**

**Desktop (please complete the following information):**
 - OS: qnap NAS OS/ Linux
 - Browser [e.g. chrome, safari] Firefox last version
 - Yacht Version [e.g. v0.0.6-alpha] last docker release

**Additional context**

** Logs **
Add any relevant logs (from the yacht docker container or from your browser console)

**Comment by SelfhostedPro** [comment]
Can you post logs from the Yacht container on your host using the `docker logs` command? It’s fairly light cpu wise so should definitely not cause issues with CPU usage.

**Comment by SkalCore** [comment]
here are the necessary logs: https://pastebin.com/NqBBQZH1

**Comment by SelfhostedPro** [comment]
Looks like the dashboard isn’t able to get the CPU usage. Is it just the dashboard that’s frozen or is it the whole GUI?  It may be a good idea to revert to v0.0.7 instead of the latest hotfix. I’ll take a look at this shortly and workout a solution for you.

**Comment by SkalCore** [comment]
https://i.imgur.com/8zmhSpT.png, its the gui and my webinterface from my Nas is very slowly...so i think i switch to an older version

**Comment by SkalCore** [comment]
ok, i tried it with two older versions. the cpu load is now back to normal, but i don't get any cpu info displayed in yacht anymore. Before that everything worked fine. Until with the last release the described errors occurred.

**Comment by SelfhostedPro** [comment]
What is the current version you’re on?

**Comment by SkalCore** [comment]
> 
> 
> What is the current version you’re on?

v0.0.6-alpha-hf1

**Comment by SelfhostedPro** [comment]
Can you try this version? It should show cpu and memory but may not show all the apps you’re running. v0.0.7-alpha-2021-05-07--12

**Comment by SkalCore** [comment]
> 
> 
> Can you try this version? It should show cpu and memory but may not show all the apps you’re running. v0.0.7-alpha-2021-05-07--12

sorry, no success with that either, not a single container is shown in the dashboard and no info regarding CPU is shown, in the logs the same message appears again and again


2021-06-01T19:43:47.304749846Z INFO:      - "GET /api/apps/stats HTTP/1.1" 404 Not Found


2021-06-01T19:43:47.309330037Z INFO:      - "GET /api/apps/stats HTTP/1.1" 404 Not Found


2021-06-01T19:43:47.310807368Z INFO:      - "GET /api/apps/stats HTTP/1.1" 404 Not Found


2021-06-01T19:43:47.315275870Z INFO:      - "GET /api/apps/stats HTTP/1.1" 404 Not Found


2021-06-01T19:43:47.356606717Z INFO:      - "GET /api/apps/stats HTTP/1.1" 404 Not Found


2021-06-01T19:43:47.360347980Z INFO:      - "GET /api/apps/stats HTTP/1.1" 404 Not Found


2021-06-01T19:43:47.362106477Z INFO:      - "GET /api/apps/stats HTTP/1.1" 404 Not Found


2021-06-01T19:43:47.581235152Z INFO:      - "GET /api/apps/stats HTTP/1.1" 404 Not Found

**Comment by SkalCore** [comment]
ok, I found the error, it was due to the cookies, after I deleted the cookies, it now works with the last version

**Comment by SteveDinn** [comment]
Just trying out the newest Firefox (typically, I'm a Chrome user), and I've just experienced this as well.

**Comment by SelfhostedPro** [comment]
Ah, I'm a fool. It's still doing a request for each app even though the one endpoint serves stats for all apps. I will get some work done to fix this shortly.

**Comment by C-Fu** [comment]
same here. current release has this problem. All I did was to either change the email from admin@yacht.local, or the password, or both

**Comment by nicjansma** [comment]
I'm hitting this as well.  I have ~60+ containers and loading Yacht freezes my browser.

![image](https://user-images.githubusercontent.com/1004649/124961039-faeb5480-dfea-11eb-8f29-bc9fc7174f2a.png)

It looks like there's a `/stats` request for each container, but each `/stats` EventStream gives data about _all_ containers.

**Comment by SteveDinn** [comment]
I've noticed that just having Yacht open in my browser makes a noticeable impact on my server's CPU temperature. I'd like to be able to leave it open in a tab in the background, but it makes my office noisy :)

**Comment by skluthe** [comment]
Everyone who’s having these issues. Can you try the devel tag to see if that resolved it? (Just spin up another instance of yacht on another port so it doesn’t affect your current one)

**Comment by nicjansma** [comment]
With `:devel`, I no longer see tons of `/api/app/stats` requests:

![image](https://user-images.githubusercontent.com/1004649/125297300-2032d800-e2f5-11eb-93d4-44ccac9ca7ee.png)

However, the page still locks up on all the browsers  I've tried (Chrome, FF, Safari).  I can't even open the Profiler in any of the browsers because the profilers hang too.

**Comment by nicjansma** [comment]
I was finally able to get a Profile with Safari.

Here's a 30.37-second trace with ~29 seconds of JavaScript CPU:

![image](https://user-images.githubusercontent.com/1004649/125298295-01811100-e2f6-11eb-9fea-7e5a89614fef.png)

Obviously this is minified code but it seems to be Vue updates.

**Comment by Spencer-Dawson** [comment]
I am seeing this issue as well. Installed through OMV5 OMV-Extras. Lots of intermittent lag loading things and getting a "KeyError: system_cpu_usage" in the logs.

**Comment by nicjansma** [comment]
Yeah Yacht is unusable for me until this is fixed.  Unfortunately I don't have any experience debugging Vue, hopefully there's a simple place it can be optimized?

**Comment by skluthe** [comment]
> Yeah Yacht is unusable for me until this is fixed. Unfortunately I don't have any experience debugging Vue, hopefully there's a simple place it can be optimized?

Unfortunately this kind of issue is hard to optimize which is why it’s taken so long. I may wind up having to just add a few seconds of delay to the dashboards in order for it not to be so resource intensive. Also is intermittent and not affecting everyone so it’s hard to nail down.

**Comment by SteveDinn** [comment]
Honestly, even requiring a manual refresh is perfectly acceptable to me. Anything is worth making it not use so many resources on both the hosting server and the client.

**Comment by nicjansma** [comment]
@skluthe thanks for taking a look.  It's 100% repro for me, given enough docker instances (I have 58 on my host).

Again I know very little about Vue, but in the past when I've seen issues like this it can be caused by the UI framework not batching UI updates together (e.g. trying to apply container 1, draw, then 2, draw, etc instead of applying container 1-58 changes together then draw).  Looks like Vue batches updates for each Tick, but maybe the way these components are being updated is confusing Vue a bit?

If it's a challenge to fix the perf issues here, I'd also be happy with what @SteveDinn says: either a control to decide how often to update (e.g. never, 1s, 2s, 5s, 10s, 30s, 60s) or a "Update Now" button.

**Comment by Spencer-Dawson** [comment]
Dev branch resolved the performance issue for me.
