### ISSUE TITLE
[Feature Request] Title

### ISSUE THREAD

**Issue by nikosgpet** [SelfhostedPro/Yacht#414]
**Is your feature request related to a problem? Please describe.**

Currently, environment variables passed to Yacht on its creation are not passed to the containers managed by Yacht. This is unfortunate because I would like to pass some environment variables from the host to Yacht and then forward them to the containers. Most notably, I want to pass the ssh-agent from the host machine to the running containers through the $SSH_AUTH_SOCK variable set by the host.

Ssh-agent is necessary to be able to easily update my gits from inside the containers themselves.

**Describe the solution you'd like**

As I understand it [by reading the code](https://github.com/SelfhostedPro/Yacht/blob/9dead849c74eed251b517ae6e912fe69c44c1fe3/backend/api/actions/compose.py#L83), this is because all environment variables are cleaned and they are not passed to the docker-compose on creation time. From my understanding, this could be relatively easily changed to pass through all available variables downwards by default instead of cleaning the environment.

**Describe alternatives you've considered**

Otherwise, I will need to manually pass the content of the variable in each container, and monitor if the contents of the variable changed to then manually update them in each docker-compose.

**Additional context**

**Comment by SelfhostedPro** [comment]
The reason why I'm cleaning it is that variables used in Yacht can interfere with variables set within docker-compose projects. A more ideal solution would be to have kind of global variable page within projects to allow them to be passed like how you want. 

Would that solution work for you or is there an alternative you would suggest?

**Comment by nikosgpet** [comment]
Sure, that could work. Would be great if it could handle the edge scenario of declaring a variable in the form `SSH_AUTH_SOCK=$SSH_AUTH_SOCK` where SSH_AUTH_SOCK is a variable we passed on to Yacht. This would allow passing to Yacht variables set by the system.
