### ISSUE TITLE
[Feature Request] Possible usage for different databases

### ISSUE THREAD

**Issue by TheAnachronism** [SelfhostedPro/Yacht#418]
**Is your feature request related to a problem? Please describe.**
Not really a problem but it would be really useful to use a different database then just sqlite. As far as I can see, that is currently the only option for data storage about projects and so on (there isn't that much data yes but still)

**Describe the solution you'd like**
Maybe it would be possible to specify per environment variables or something what kind of database connection should be used.

**Describe alternatives you've considered**
Well nothing really.

**Comment by skluthe** [comment]
You can specify a MySQL database using the DATABASE_URL environment variable. All that’s stored in the DB is user creds (hashed) and templates.

**Comment by SelfhostedPro** [comment]
Here is an example: https://fastapi.tiangolo.com/tutorial/sql-databases/

(First code lock with database url)

**Comment by TheAnachronism** [comment]
Ah ok, well never mind I didn't know that.
Thx for the quick answer and the awesome tool!
