### ISSUE TITLE
[Feature Request] Support tcp docker socket

### ISSUE THREAD

**Issue by kaysond** [SelfhostedPro/Yacht#429]
**Is your feature request related to a problem? Please describe.**
For security reasons, I don't want to mount the docker socket into the container

**Describe the solution you'd like**
Other services, like traefik, allow you to specify a tcp socket to use to send requests to the docker daemon. You can then use something like [tecnativa/docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy) to control what docker APIs yacht can access 

**Describe alternatives you've considered**
none

**Comment by SelfhostedPro** [comment]
#107 has the solution to this. Set the DOCKER_HOST env variable in the run command for Yacht and it’ll do what you want. More details and a link to the docker documentation are in that ticket.

**Comment by kaysond** [comment]
Thanks!
