### ISSUE TITLE
[Feature Request] Ability to control remote docker servers

### ISSUE THREAD

**Issue by jnash67** [SelfhostedPro/Yacht#434]
Killer feature would be the ability to control containers not just on the local machine but on remote machines as well

**Comment by SelfhostedPro** [comment]
#429 has the solution

**Comment by jnash67** [comment]
Thx.  Does that work for multiple remote machines?  If so then perhaps the request should be amended to integrate that functionality into Yacht.  Yacht makes managing Docker much easier.  Having to figure out Docker Socket Proxy makes it hard again.

**Comment by SelfhostedPro** [comment]
It’s not a feature of yacht. Just something docker itself provides. At some point I will look at adding multi server support but I haven’t had time to work on it lately. 
It will only work once per instance of yacht.
