### ISSUE TITLE
[Bug Report] ~/ not being handled correctly in Bind Mounts

### ISSUE THREAD

**Issue by Narflar** [SelfhostedPro/Yacht#435]
**Describe the bug**
if I set a bind mount to ~/ ,Yacht is registering that as /config instead of /home/user.  When I use docker-compose directly ~/ is being treated as home.

**To Reproduce**
Running the below docker-config.yml in Yacht Project and Docker-Compose produce two different results.

        volumes:
            - ~/.docker/data/speedtest:/config
    
**Expected behavior**

I expect Yacht to mirror how Docker-Compose handles the home shortcut

**Screenshots**

When I inspect the container that was installed via Yacht Project I see the following

"Binds": [
                "/config/.docker/data/speedtest:/config:rw"
            ],
       

When I inspect the container that was installed via docker-compose I see the following

"Binds": [
                "/home/user/.docker/data/speedtest:/config:rw"
            ],

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04.3 LTS ]
 - Browser [Chrome]
 - Yacht Version [e.g. v0.0.6-alpha]
 - "build_version": "Linuxserver.io version:- 3e3be7bf-ls22 Build-date:- 2021-04-20T12:55:46+01:00",

**Additional context**
I set PUID and GUID to 1000 when installing Yacht

**Comment by SelfhostedPro** [comment]
Yacht is running inside of a container, therefor it has no idea what your user account is or where home is. 

You can set a template variable for !home to an absolute path to your home directory (ie. /home/user/) and use that in templates. 

For projects, you’ll want to use an absolute path as that is the recommended best practice from the docker-compose maintainers iirc.

**Comment by SelfhostedPro** [comment]
/config is the “home” of the yacht container which is why you’re seeing that specific path.

**Comment by Narflar** [comment]
Ok, that makes sense.  I couldn't figure out why things were working differently.  Thank you!

**Comment by SelfhostedPro** [comment]
You could probably sort it out by passing the $HOME environment variable to The Yacht container with the value you want ~ to have.
