### ISSUE TITLE
Nothing is being displayed

### ISSUE THREAD

**Issue by PaulMcF1987** [SelfhostedPro/Yacht#437]
More often than not, when I log onto Yacht, there is nothing displayed.
Occasionally, there are containers shown on the dashboard but if I navigate to a different screen and then navigate back, the screen stays blank.

None of the tabs under `Resources` (Images, Volumes, Networks) show anything, there is a constant loading bar which shoots across the top if the screen,

The only tab that consistently works is the `Applications` tab this always gives a list, however if I try to use the dropdown to start,stop update an app, it tells me that it is performing the requested action but never actually finishes...

I have pasted the Logs (I have removed quite a few lines as `    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized...   INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized` tends to take up most lines)

    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/login HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/ HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK

Also I cant seem to view stacks via Yacht is this something that I should be able to view?

**Comment by skluthe** [comment]
It looks like the refresh token expires but the login redirect isn't consistent. Try refreshing with control+shift+r and it should have you login or try logging out and back in.  If you try the devel image (selfhostedpro/yacht:devel) it should help resolve this issue.

As far as stacks go, those are proprietary to Portainer. If you have a directory of docker-compose projects, you can mount that into /compose within the container and you'll see them. If not, Yacht has no way of interacting with the Portainer container to see what stacks there are or manage them.

**Comment by PaulMcF1987** [comment]
@skluthe 
I had already tried logging out and back in. I have now tried the `devel` release and getting the same problems

      
    [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
    [s6-init] ensuring user provided files have correct perms...exited 0.
    [fix-attrs.d] applying ownership & permissions fixes...
    [fix-attrs.d] done.
    [cont-init.d] executing container initialization scripts...
    [cont-init.d] 01-envfile: executing... 
    [cont-init.d] 01-envfile: exited 0.
    [cont-init.d] 10-adduser: executing... 
    usermod: no changes
    -------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
    Brought to you by linuxserver.io
    -------------------------------------
    To support LSIO projects visit:
    https://www.linuxserver.io/donate/
    -------------------------------------
    GID/UID
    -------------------------------------
    User uid:    911
    User gid:    911
    -------------------------------------
    [cont-init.d] 10-adduser: exited 0.
    [cont-init.d] 30-config: executing... 
    [cont-init.d] 30-config: exited 0.
    [cont-init.d] 31-migrate: executing... 
    INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
    INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
    INFO  [alembic.autogenerate.compare] Detected removed index 'ix_jwt_token_blacklist_jti' on 'jwt_token_blacklist'
    INFO  [alembic.autogenerate.compare] Detected removed table 'jwt_token_blacklist'
    INFO  [alembic.autogenerate.compare] Detected removed index 'ix_secret_key_key' on 'secret_key'
    INFO  [alembic.autogenerate.compare] Detected removed table 'secret_key'
    --- MODELS ---
    Generating /alembic/versions/8eaae61d829e_automated_db_upgrade.py ...  done
    INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
    INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
    INFO  [alembic.runtime.migration] Running upgrade  -> 8eaae61d829e, automated db upgrade
    --- MODELS ---
    [cont-init.d] 31-migrate: exited 0.
    [cont-init.d] 32-env: executing... 
    Replacing env constants in JS
    Processing /app/js/app.7eadd55c.js ...
    Processing /app/js/app.7eadd55c.js.map ...
    Processing /app/index.html ...
    [cont-init.d] 32-env: exited 0.
    [cont-init.d] 90-custom-folders: executing... 
    [cont-init.d] 90-custom-folders: exited 0.
    [cont-init.d] 99-custom-files: executing... 
    [custom-init] no custom files found exiting...
    [cont-init.d] 99-custom-files: exited 0.
    [cont-init.d] done.
    [services.d] starting services
    [services.d] done.
    INFO:     Started server process [336]
    INFO:     Waiting for application startup.
    INFO:     Application startup complete.
    INFO:     Uvicorn running on unix socket /tmp/gunicorn.sock (Press CTRL+C to quit)
    Secret key generated
    Secret key exists
    DISABLE_AUTH = False (<class 'bool'>)
    Users Exist
    Template Variables Exist
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/apps/ HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/login HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/ HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
    INFO:      - "GET /api/apps/stats HTTP/1.1" 200 OK
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/apps/ HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
    INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
    INFO:      - "POST /api/auth/login HTTP/1.1" 400 Bad Request

**Comment by PaulMcF1987** [comment]
@SelfhostedPro 
I have cleared the cache and the version has changed to `Version: devel-2021-12-04--00`

Can I ask what the difference is with the devel version and the standard released versions?

**Comment by SelfhostedPro** [comment]
Devel has some bug fixes related to requests in the dashboard, update checks, and removes PWA functionality as the caching involved has been causing issues when updates are released (which is what you ran into after changing). I’m just waiting for feedback on the devel branch and need to fix an issue with it (ui freezes for one person running ~50 apps). Once that’s resolved I’ll be merging into master and releasing a new `latest` image.
