### ISSUE TITLE
[Bug Report] Why is Yacht container not showing up as Yacht in webui?

### ISSUE THREAD

**Issue by ozdeadmeat** [SelfhostedPro/Yacht#439]
**Describe the bug**
The Yacht container has a random name. How can I have it persistently say Yacht?

**Comment by SelfhostedPro** [comment]
You can use the `--name` flag in your docker run command to set a name for the container.

**Comment by X1pheR** [comment]
And if you use compose use  container_name:nameyoulike

**Comment by wickedyoda** [comment]
Unless you use the --name switch or specify the container name in docker-compose; docker creates random names for containers. This isn't a yacht issue but how docker works.
