### ISSUE TITLE
Request Removal of Third Party Components.

### ISSUE THREAD

**Issue by di-org** [SelfhostedPro/Yacht#440]
"I am frustrated when...." I choose to Selfhost an app, particularly an administrative app (Yacht), that is coded to call to a 3rd party.

Yacht connects to fonts.googleapis.com and cdn.jsdelivr.net.  If this administrative tool is properly isolated on a network/host, it ends up trying and failing to connect to off-network hosts.

This app is truly not self-hosted if it requires components hosted on 3rd parties, and worse if using a bad actor's infrastructure, like Google.

`<link rel=stylesheet href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900"><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.min.css>`

**Comment by SelfhostedPro** [comment]
Sure, if you’d like to provide a PR to remove these components and replace them with an alternative I’d be happy to accept it. 

I’m not a developer for my dayjob so I went with options that made it easier to provide features and build the app quickly. 

One byproduct of that is a few external dependencies for fonts and ui components. I’m happy to have them removed but I don’t have the expertise to replace them in an amount of time that makes sense nor the ability to dedicate the amount of time that would take.

**Comment by di-org** [comment]
Unfortunately, I am an infrastructure security type, and have zero coding capabilities other than my daily bash scripts.  I'll close this out.

**Comment by SelfhostedPro** [comment]
I don’t think it needs to be closed so I’m going to reopen it and will update here with progress if I’m able to get some time to work on it. Just don’t want to promise anything just in case.

**Comment by Code-Slave** [comment]
for reference
https://answers.themler.io/articles/9064/how-to-use-google-fonts-locally

**Comment by wickedyoda** [comment]
@Code-Slave we have not forgotten about you, please follow this branch as we look into removing the fonts and Google links you requested. [Request removed of third part components.](https://github.com/SelfhostedPro/Yacht/tree/Request-Removal-of-Third-Party-Components.-%2344)
