### ISSUE TITLE
[Bug Report] Unprocessable Entity: [object Object]  When attempting to change network profile of containers

### ISSUE THREAD

**Issue by fisherd80** [SelfhostedPro/Yacht#442]
**Describe the bug**
When attempting to change the network profile for the Wireguard container after it being created by docker-compose, the changes would not implement and the error "Unprocessable Entity: [object Object]" is shown.

I don't know what is causing this or if it is relating to Yacht.

**To Reproduce**
Steps to reproduce the behaviour:
1. Opened the container "Wiregaurd" throught the Application panel.
2. Stopped the container.
3. Clicked edit and moved to "Network".
4. Selected the network I wanted to change.
5. Moved to the end to confirm this change.
6. The above error is returned and the new settings are not applied.

**Expected behavior**
The container would restart with the new network profile.  Allow it to see the other containers on this network.

**Screenshots**
![image](https://user-images.githubusercontent.com/31191953/151667059-68b89e50-bdc1-4e22-b76f-09e2da1d01d7.png)
![image](https://user-images.githubusercontent.com/31191953/151666792-28280cd7-e88b-4d7e-910f-d8c383f11158.png)

**Desktop (please complete the following information):**
OS: DietPi (arm64 v:11 (bullseye)) - all updates done
Hardware: RPi 4 Model B (aarch64)
Yacht Version: Version: v0.0.7-alpha-2021-05-31--16

Any help would be greatly appreciated, as never come across this error before.

**Comment by SelfhostedPro** [comment]
Hmmmm. It looks like an issue with formatting. Can you try upgrading to the :devel branch or running it in parallel with your current one? (Template here: https://github.com/SelfhostedPro/yaml_test/raw/master/yacht-dev.yml )

**Comment by wickedyoda** [comment]
Please update the ticket with the issue's current status, if resolved please let us know and close the ticket.

**Comment by amarevite** [comment]
I've experienced a similar (perhaps the same) issue. When making any changes at all, they would not be saved. My issue turned out to be that the name for my sysctls variable was not saving (but the value was). Adding the name of the variable let me proceed as normal.
![image](https://user-images.githubusercontent.com/35640607/192435781-4f22b412-29d5-4cb2-b408-d74641a1cd9a.png)

**Comment by marksherman** [comment]
I'm getting the same thing when I try to edit any property. I switched to `:devel` and it's the same. Is there anything I can do? Recreating each container from scratch whenever I need to tweak something is a little tiring 😅 

<img width="415" alt="Screenshot 2023-01-28 at 12 08 38 PM" src="https://user-images.githubusercontent.com/2035149/215279565-e9b9bb87-0447-4085-acac-9bd78a9da75e.png">

**Comment by wickedyoda** [comment]
This is a known issue, and we are working on it currently.

![image](https://user-images.githubusercontent.com/68271168/215288777-2f0325c1-2ca4-4d4d-9643-1492605b4939.png)

**Comment by wickedyoda** [comment]
![image](https://user-images.githubusercontent.com/68271168/215288990-3a5ad6f5-9d51-4e10-a6c3-4fa03b0cd269.png)

**Comment by wickedyoda** [comment]
The same issue is happening on the nightly build. @SelfhostedPro
