### ISSUE TITLE
my Dashboard is empty but Application are installed

### ISSUE THREAD

**Issue by eskimos2000** [SelfhostedPro/Yacht#444]
Hi,

I did a fresh install on Raspbian Lite, docker and Yacht all went seemed ok, so I installed a few apps (sonarr, lidarr, sabnzbd etc) all is working well but my dashboard is empty, I have added that txt suggested for ARM (I use pi4) to cmdline.txt rebooted and still nothing on the dashboard. I am a bit of a noob so maybe I am doing something wrong? 

![2022-02-01](https://user-images.githubusercontent.com/42510582/151911104-d69b23a4-0f5d-4baf-8603-f7fe9d5a4c48.png)

**Comment by SelfhostedPro** [comment]
If you run `docker stats` does anything come up? Do they show on your applications list?

**Comment by eskimos2000** [comment]
Yeah on yacht app tab and cli
![2022-02-01 (1)](https://user-images.githubusercontent.com/42510582/151923507-c7eabc2c-a41a-43e3-8e75-d9a794be625a.png)
![2022-02-01 (2)](https://user-images.githubusercontent.com/42510582/151923510-1ff832af-dd23-46d5-89ee-d8439d00711a.png)

**Comment by pingywon** [comment]
Hey awesome thanks. I had all that in my config, but apparently I had some other nonsense too. Yacht is now working as expected. 

Thanks

**Comment by pingywon** [comment]
The Templates page is still not reliably showing up through Nginx.

**Comment by pingywon** [comment]
Also can not log out.

**Comment by eskimos2000** [comment]
I do not rather. I have OMV 6 with docker and Yacht installed on
RaspbianLite bullseye.

**Comment by SelfhostedPro** [comment]
Make sure you clear your cache (control+shift+r) as there’s some aggressive caching that will be removed once I sort some build issues out and can push an update.

**Comment by pingywon** [comment]
Still no dice. The dashboard is hit or miss. more hit than miss and templates just zooms across the top and only displays my template sometimes.

**Comment by SelfhostedPro** [comment]
Anything in your logs?

**Comment by SelfhostedPro** [comment]
> I do not rather. I have OMV 6 with docker and Yacht installed on RaspbianLite bullseye.
> […](#)

Make sure you follow the arm instructions in the documentation on https://yacht.sh

**Comment by wickedyoda** [comment]
Please update the ticket with the issue's current status, if resolved please let us know and close the ticket.

**Comment by pingywon** [comment]
Still an issue it just seemed like everyone was blaming it on Chrome caching. I cleared everything you can in Chrome, even tried  incog mode and it still does the same thing. the sub banner just zooms across the screen. Now if I use it in Firefox, it works perfectly. So yeah, its super annoying, but the few times I need to get in there I use Firefox and just have let sleeping dogs lie.

**Comment by eskimos2000** [comment]
Hi, I have reinstalled raspbian and yacht and so far everything is working now, so I reckon I can close the issue.

**Comment by pingywon** [comment]
> Are you in our discord? It's not the main pathway for support but maybe one of us can work with you one on one to gather more information about the error.
> 
> https://discord.io/selfhostedpros

I am. I will ping you or post to a channel. I am same name on discord. 

Im not sure it is something in nginx that is proxying wrong. It does not work on chrome or safari mobile, but works just fine in Fire Fox.

anyway - yeah I would love a solve for this. Ill pop in Discord and share whatever details youd like.

Thanks!

**Comment by eskimos2000** [comment]
Yes
