### ISSUE TITLE
Where to find main repository with SDRTemplates for Yacht?

### ISSUE THREAD

**Issue by denisgolius** [SelfhostedPro/Yacht#445]
Hi team!

Where to find main repository with SDRTemplates for Yacht? I want to create and add my own templates to this repository that help users to see and use my software in Yacht,  but I can't anything like this. Any advice?

I mean this https://youtu.be/zaEbecZm7Zc?t=545

**Comment by SelfhostedPro** [comment]
Hi, that repo is located here: https://github.com/SelfhostedPro/selfhosted_templates

I am working on updating it to be compatible with Shipwright: https://shipwright.yacht.sh

**Comment by denisgolius** [comment]
> Hi, that repo is located here: https://github.com/SelfhostedPro/selfhosted_templates
> 
> I am working on updating it to be compatible with Shipwright: https://shipwright.yacht.sh

Thanks!
PS: how I can test my own software after adding to some json file ?

**Comment by SelfhostedPro** [comment]
You’ll want to fork the repo with templates, make your changes there, and reference the raw GitHub url to add it to Yacht. You can also host the template alone on a webserver.

**Comment by SelfhostedPro** [comment]
If you run into any issues, feel free to reach out. Have a good one!
