### ISSUE TITLE
[Feature request] Option to set sidebar to open position

### ISSUE THREAD

**Issue by brantje** [SelfhostedPro/Yacht#452]
Hi!
Love the software :)
1 small thing i would like to have the sidebar always show, maybe clicking on the logo would make it expand / collapse?

**Comment by wickedyoda** [comment]
Can you please provide more details, system configuration, and screenshots?

**Comment by kizza42** [comment]
I too would love to have this, its annoying to have to wait for the animation to expand the sidebar when looking for a menu entry. Would much prefer to always have direct links to everything like this:
![image](https://user-images.githubusercontent.com/12605257/173495583-f3f14a9c-468b-4f56-91fe-713e80da622c.png)

**Comment by drbraden** [comment]
I would love this option, too.  I want the sidebar to either:

1. stay closed (icon only)
2. stay open (icon and text)
3. or have a link/icon that toggles it open & closed (and stays that way unless toggled again)

To me the autohide is very annoying, and when expanded it obscures the left side of the page's content until it hides again.
