### ISSUE TITLE
[Bug Report] Unable to import portainer based templates

### ISSUE THREAD

**Issue by McFuzz89** [SelfhostedPro/Yacht#456]
Hi! 

Complete docker n00b here - but decided to dive in with Yacht as it seems the most user-friendly, un-bloated management platform. One thing I encountered is inability to add templates aside from the generic one provided by the tool itself. For example - I am trying to import this template (portainer template): https://raw.githubusercontent.com/dnburgess/self-hosted-template/master/template.json

However every yacht errors out simply stating "Internal Server Error: undefined" 

I noticed the template format is a bit different than the generic one, but the repo docs seems to indicate yacht is compatible with portainer templates...

Thanks!

**Comment by McFuzz89** [comment]
Hi! So I tried converting the template using shipwright, however even though the template can now be loaded, i still get an undefined error when I try to view it. The example I used is this template: 

https://raw.githubusercontent.com/ntv-one/portainer/main/template.json

any ideas?

**Comment by SelfhostedPro** [comment]
Minio and CockroachDB need brackets `[]` around the argument in the `command:` section (ie. `command": ["start --insecure"]`). There are also some apps missing images. I think just adding the brackets around commands should fix it though. I'll change this behavior in the future so I'll leave this ticket open to remind me.

The template I tested with is here: https://raw.githubusercontent.com/SelfhostedPro/yaml_test/master/Imported%20Template-yacht.json

**Comment by McFuzz89** [comment]
Gotcha - thank you for the help!! Good to know what to look for the next time I encounter this issue... Thanks again!

**Comment by wickedyoda** [comment]
@McFuzz89 Confirm please that the issue is resolved, if not please update the ticket; if so please update and close. 

Thank you!
