### ISSUE TITLE
[Feature Request] Docker-Compose for Dev use

### ISSUE THREAD

**Issue by marcjmiller** [SelfhostedPro/Yacht#459]
**Is your feature request related to a problem? Please describe.**
Yacht could use a good docker-compose to help bring on additional devs by lowering the barrier to entry for contributors.

**Describe the solution you'd like**
A docker-compose with profiles for dev/prod (though prod will still use the built container ultimately)

**Describe alternatives you've considered**

**Additional context**
I'll do up a compose right quick to add to this.

**Comment by wickedyoda** [comment]
See pull request [Yacht/pull/460](https://github.com/SelfhostedPro/Yacht/pull/460), adding docker-compose.yml to the base directory so it can be used as an example for Devs and users alike.

**Comment by wickedyoda** [comment]
Resolved.
