### ISSUE TITLE
[Feature Request] 2FA with TOTP

### ISSUE THREAD

**Issue by ontheair81** [SelfhostedPro/Yacht#461]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a request about a more secured login, not just by e-mail and password.

**Describe the solution you'd like**
It would be great if 2FA with TOTP could be added.

**Describe alternatives you've considered**
Maybe some kind of rate limiting for logins could be helpful, too, but having real 2FA would be the best, in my opinion.

**Additional context**
Thank you very much for this great project!

**Comment by SelfhostedPro** [comment]
Sure, I’ll add it to the todo list. Thanks for the recommendation.
