### ISSUE TITLE
[Feature Request] import templates from file

### ISSUE THREAD

**Issue by deadc0de6** [SelfhostedPro/Yacht#467]
**Is your feature request related to a problem? Please describe.**

Adding templates expects these to be available *online*. It would be nice if it was possible to import a local created/modified template file from the web interface.

**Describe the solution you'd like**

The ability to import a template from a local file.

**Describe alternatives you've considered**

Currently my workaround is to pop a small `python3 -m http.server` to serve the file.

**Comment by SelfhostedPro** [comment]
You should be able to mount it into your container and use the file:// url path to your template to import it.

**Comment by deadc0de6** [comment]
oh good to know, thanks for the info. 
Would be nice to see that info in the documentation and a volume [in the docker-compose](https://yacht.sh/docs/Installation/Install#via-docker-compose).
