### ISSUE TITLE
Cannot access anything due to permission error

### ISSUE THREAD

**Issue by JuxtaCode** [SelfhostedPro/Yacht#474]
**Describe the bug**
I have successfully installed Yacht on Windows 11 and I am able to log in and see the interface, but when I try to access any of the sections I get an orange error message at the bottom of the screen that says 
Internal Server Error: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))

**To Reproduce**
Install Yacht
Log in
Try to do anything.

**Expected behavior**
I expect to see something

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome or Brave
 - Yacht Version: v0.0.7-alpha-2022-04-26--21

**Comment by JuxtaCode** [comment]
That was fast. I actually ended up using the docker compose instructions for MAC and it works great. Thanks.

**Comment by wickedyoda** [comment]
If you don't mind, post what you were using first and what you got to work. I am interested in seeing why, if there is something wrong I can update the documents. Also here (https://github.com/SelfhostedPro/Yacht/blob/master/docker-compose.yml) is the docker-compose we give as examples; it's not the one I use. Mine has some added options to it but basics will get you going. So far it's worked on all host OS that I have tested.

**Comment by JuxtaCode** [comment]
I just followed these instructions first: https://yacht.sh/docs/Installation/Getting_Started/

So I just ran these commands:
docker volume create yacht
docker run -d -p 8000:8000 -v /var/run/docker.sock:/var/run/docker.sock -v yacht:/config selfhostedpro/yacht

That did not work so I noticed that the instructions for MacOS (https://yacht.sh/docs/Installation/Mac) said that Mac may throw a permissions issue, so I gave it a shot and it worked. I just created using this docker-compose.yml:

version: '3'
services:
  yacht:
    container_name: yacht
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /Projects/compose:/compose
    environment:
      - PUID=0
      - PGID=0
      - COMPOSE_DIR=/compose
    image: selfhostedpro/yacht
volumes:
  yacht:
