### ISSUE TITLE
[Bug Report] Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by wuchang1123** [SelfhostedPro/Yacht#475]
**Describe the bug**
The Dashboard panel display is blank, and the request error is seen in the debugging tool

**To Reproduce**
docker run -d -p 8000:8000 \
    -e ADMIN_EMAIL=test@test.com \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v yacht:/config \
    --name yacht \
    selfhostedpro/yacht

**Screenshots**
![rerertt5r](https://user-images.githubusercontent.com/565671/167080601-11b41a25-8023-430e-8211-ced1e808f021.PNG)

**Logs**

2022/05/06 06:21:45 [error] 371#371: *795 upstream prematurely closed connection while reading upstream, client: 10.x.x.x, server: , request: "GET /api/apps/stats HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/apps/stats", host: "10.x.x.x:8000", referrer: "http://10.x.x.x:8000/"

**Comment by wuchang1123** [comment]
![rerertt5r](https://user-images.githubusercontent.com/565671/167080107-381a9d54-6350-4b2e-8ed6-ba0612022a01.PNG)

**Comment by ftl-devs** [comment]
Hi I am having the same issue with my raspberry pi 4

**Comment by anpct** [comment]
Hi I am having the same issue with my raspberry pi 4

**Comment by pedroapfilho** [comment]
Seeing the same issue here on my raspberry pi
