### ISSUE TITLE
[Feature Request] Title

### ISSUE THREAD

**Issue by kcoderhtml** [SelfhostedPro/Yacht#483]
**Is your feature request related to a problem? Please describe.**
Badges would make the cards easier.

**Describe the solution you'd like**
I would icons to be added to containers like the logo for bitwarden or dashy. 

**Describe alternatives you've considered**
Nothing changes

**Additional context**
I saw this mentioned on the Awesome Open Source youtube channel https://youtu.be/eTQ2iB-hjkk?t=550

**Comment by wickedyoda** [comment]
Keeping up with icons for many containers becomes an issue; companies are constantly updating, changing, and modifying. Then comes the issue of copyrights and permissions to use the logos. Unfortunately, this won't be a priority to implement; you have "coder" in your name; if you're familiar with coding, work up a repo, and we would be glad to push to master once tested. Find us @ https://discord.io/selfhostedpros

**Comment by kcoderhtml** [comment]
Thank you for your time explaining.
