### ISSUE TITLE
[Bug Report] Commands not working

### ISSUE THREAD

**Issue by LuanHimmlisch** [SelfhostedPro/Yacht#486]
**Describe the bug**

Commands don't work. When deploying  a container it always fails, it doesn't detect any folder and fails with the more simple commands.

**To Reproduce**

Just add a command.

**Expected behavior**

That the commands execute correctly.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 Cinnamon
 - Yacht Version: v0.0.7-alpha-2022-05-11--03

**Logs**

When trying to do cp

```
/usr/local/bin/docker-php-entrypoint: 9: exec: cp /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/: not found
```

Testing with a simple ls also causes an error.
```
/usr/local/bin/docker-php-entrypoint: 9: exec: ls /etc/: not found
```

Even if using the full binary path

```
/usr/local/bin/docker-php-entrypoint: 9: exec: /bin/ls /: not found
```

The only time it didn't logged anything but still failed to start the container was when trying to do a ls without path.

**Comment by SelfhostedPro** [comment]
Can you paste exactly what you’re putting in the command field? Typically you’ll need to use multiple commands in order for it to work correctly:

in the following, each line is a command:
```
ls
/etc
```

**Comment by LuanHimmlisch** [comment]
@SelfhostedPro sure, every command I've tried:

```
a2enmod rewrite
cp /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/
ls /
ls /etc/
/bin/ls /etc/
/bin/ls /
/bin/ls
```

None works

**Comment by LuanHimmlisch** [comment]
When executing `/bin/ls` it didn't log anything but didn't run the container also. This may be a docker problem but I can run commands when using docker manually instead of Yacht

**Comment by LuanHimmlisch** [comment]
I've also noticed that no template of selfhosted_templates uses commands. So maybe this is something overlooked?

**Comment by SelfhostedPro** [comment]
There are templates that successfully use commands. You need to separate the executable and arguments like you would using the CMD in a docker container. Separate `/bin/ls` and `/etc` into 2 separate commands as an example.

**Comment by LuanHimmlisch** [comment]
If you could share an example of a template with commands, I will be very grateful. If a template with commands already works fine, I'll suppose it's a problem with docker on my machine and can close the issue

**Comment by wickedyoda** [comment]
Do you have discord? We have a selfhosted community where we can assist with yacht and other types of troubleshooting needs. We would be able to voice chat and screen share with you to provide additional help. It's not a replacement to GitHub issues but a tool that we use alongside for easier communication.

**Comment by SelfhostedPro** [comment]
Can you post a screenshot of how you’re entering them in the UI? It sounds like you’re putting the command and arguments in the same line. Will work on finding a template for you shortly.
