### ISSUE TITLE
[Feature Request] Icons for Containers

### ISSUE THREAD

**Issue by kcoderhtml** [SelfhostedPro/Yacht#487]
**Is your feature request related to a problem? Please describe.**
When looking at all the cards, they can blend together and make it hard to pick out one in a hurry.

**Describe the solution you'd like**
Adding icons to the cards as suggested by [Awesome SelfHosted](https://youtu.be/eTQ2iB-hjkk?t=550) on Youtube.

**Describe alternatives you've considered**
Doing nothing

**Additional context**
[Icon Repo](https://github.com/walkxhub/dashboard-icons)

**Comment by thorrrr** [comment]
Yes it would look so much better 
Like you can in Unraid 
https://i.imgur.com/CnGsODl.png

**Comment by SelfhostedPro** [comment]
I could add a label similar to how port labels work in order to allow this. I’m starting to get back into the swing of things and this could be an easy win.
