### ISSUE TITLE
Error running with Podman

### ISSUE THREAD

**Issue by Code-Quake** [SelfhostedPro/Yacht#488]
**Describe the bug**
When I try to run Yacht with Podman I get this error: statfs /var/run/podman/podman.sock: permission denied

**To Reproduce**
1. Install Podman
2. Open the terminal
3. Run podman run -v /var/run/podman/podman.sock:/var/run/docker.sock -v yacht:/config -p 8000:8000 --name -d ghcr.io/selfhostedpro/yacht:latest
4. See error statfs /var/run/podman/podman.sock: permission denied

**Expected behavior**
Yacht runs

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Yacht Version current version (don't know number)

**Additional context**
Yacht worked great with Docker 

** Logs **
None

**Comment by Code-Quake** [comment]
Never mind, I got it working. Just had to add a name to the command and set podman to rootful using the following commands:

podman machine set --rootful

podman run -v /var/run/podman/podman.sock:/var/run/docker.sock -v yacht:/config -p 8000:8000 --name -d ghcr.io/selfhostedpro/yacht:latest

**Comment by modzilla99** [comment]
With SELinux enabled I had to grant uvicorn access to read the docker/podman socket. This can be easily done with `audit2allow` although it should be noted by doing that you grant that process access to read any socket if the posix permissions allow it of course.

```bash
$ audit2allow -aM uvicorn
$ semodule -i uvicorn.pp
```

If you want to make a specific folder accessible within containers without the `:Z` it can be given the `container_file_t` type. 
```bash
$ semanage fcontext -a -t container_file_t '/my/data(/.*)?'
$ restorecon -vr /my/data
```

Now you can use podman like docker without caring about selinux contexts!
