### ISSUE TITLE
[Bug Report] Available updates not showing

### ISSUE THREAD

**Issue by tnagels** [SelfhostedPro/Yacht#496]
**Describe the bug**
Interface does not show that an update is available for a container.

**To Reproduce**
1. Go to 'Applications'
2. Click on 'Update'
3. Scroll down to 'Containers'
4. See error => no green dots next to containers with updates I am sure updates are available and when I use the "update" function it works.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: OSX, iOS
 -  Browser Safari
 - Yacht Version v0.0.7-alpha-2022-06-03--21

**Additional context**
An implementation as in the latest Portainer Business would be great:
 - Green: up to date
 - Red: update available
 - Grey: not updatable (not on the hub) 

** Logs **
Add any relevant logs (from the yacht docker container or from your browser console)

**Comment by wickedyoda** [comment]
When you click update, a watchdog instance spins up to check for the updates on the containers one by one, then downloads the images and reloads the containers. This is not an instant click and done, depending on the number of containers and the speed of your connections downloading the new images; it can take a few mins or longer. Ref: https://yacht.sh/docs if you need more information. You can also join support @ https://discord.io/selfhostedpros if you wish to communicate with us directly.
