### ISSUE TITLE
[Feature Request] Ability to manage multiple docker servers

### ISSUE THREAD

**Issue by damies13** [SelfhostedPro/Yacht#498]
**Is your feature request related to a problem? Please describe.**

I just learned about Yacht today from this YT video https://youtu.be/eTQ2iB-hjkk and then had a quick read of the documentation, I couldn't see anywhere in the documentation how you can connect to other docker servers, so if this feature already exists maybe it's just missing in the documentation?

**Describe the solution you'd like**
Ability to add additional docker servers and manage them all from this single interface

**Describe alternatives you've considered**
I've been looking for an open source solution that will allow me to manage all my docker servers from a single point, Yacht looks like a great tool for managing a single docker server, but could be better if you could add additional servers and manage them all from the same place.

p.s. Not expecting any priority on this issue, consider it a nice to have

**Comment by wickedyoda** [comment]
That's a project in the works, for now there isn't a feature. Check the projects tab.

**Comment by mailinglists35** [comment]
@wickedyoda I am unable to figure out how to use github to follow activity in a project. also they seem to be listed in some legacy form and when you click the projects tab, it shows nothing.

how can we watch for multiple environments feature coming out?
