### ISSUE TITLE
[Feature Request] Create template from manual created container

### ISSUE THREAD

**Issue by glennthielman** [SelfhostedPro/Yacht#500]
It would be nice if there is a way to generate a template from a manual created container, without the use of a template.
That way a user can easily back-up his configuration or even share one.

**Comment by wickedyoda** [comment]
This comes down to docker-compose, using it will create a file that will rebuild the container the exact same every time. So, if the data is in the same location then it will start as if nothing happens. This is also why PR is so nice, people can always take and add features themselves like this and then create a PR so it's added to the main project.

**Comment by glennthielman** [comment]
That's indeed a valid point, no need to reinvent the wheel.
You can use docker-compose for the setup and let yacht monitor the running container.
