### ISSUE TITLE
Files named compose.yml/compose.yaml are not recognized in a COMPOSE_DIR directory

### ISSUE THREAD

**Issue by MetalArend** [SelfhostedPro/Yacht#502]
Docker compose's recommendations say that the preferred name for a docker compose file is compose.yml. But Yacht does not recognize that filename.

**Comment by wickedyoda** [comment]
Unless things have recently changed it's supposed to be docker-compose.yml, please link to the documentation you referencing. @MetalArend

**Comment by MetalArend** [comment]
@wickedyoda There you go: https://docs.docker.com/compose/compose-file/#compose-file

**Comment by SelfhostedPro** [comment]
Currently it needs to be named docker-compose.yaml. The version of docker-compose doesn’t support compose.yaml yet. Working on updating but running into some issues.

**Comment by SelfhostedPro** [comment]
Typically it’ll be in /config/compose/$foldername/docker-compose.yaml. You can create a new project in the ui to see where it gets created too. 

Definitely will add that in and check the python docker library to see if they have new compose options too. Thanks for the heads up!

**Comment by queeup** [comment]
I think it's time to add `compose.yaml` & `compose.yml` file to supported file name.

https://docs.docker.com/compose/compose-application-model/
