### ISSUE TITLE
[Bug Report] Title i cant reach yacht web GUI

### ISSUE THREAD

**Issue by MaJoRX0** [SelfhostedPro/Yacht#505]
**Describe the bug**
yacht running fine in my server localhost which is 127.0.0.1
but I cant access it from any other device 

**To Reproduce**
after running yacht via docker everything looks fine but I cant access it from any other device I change the 8000:8000 to 8001:8000 idk if that is the problem or what

**Expected behavior**
I'm trying to use yacht GUI but I cant access the web GUI 

**Screenshots**
![image](https://user-images.githubusercontent.com/45786523/181040101-d8a3c217-99d8-4232-aec9-29a4090fc805.png)

**Desktop (please complete the following information):**
 - OS: running yacht on ubuntu server
 - Browser opera gx
 - Yacht Version idk but I installed the latest version

** Logs **
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 31-migrate: executing...
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'template_variables'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_variables_replacement' on '['replacement']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_variables_variable' on '['variable']'
INFO  [alembic.autogenerate.compare] Detected added table 'templates'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_templates_title' on '['title']'
INFO  [alembic.autogenerate.compare] Detected added table 'user'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_user_email' on '['email']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_user_id' on '['id']'
INFO  [alembic.autogenerate.compare] Detected added table 'apikeys'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_apikeys_id' on '['id']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_apikeys_jti' on '['jti']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_apikeys_key_name' on '['key_name']'
INFO  [alembic.autogenerate.compare] Detected added table 'template_item'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_item_name' on '['name']'
INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_item_title' on '['title']'
--- MODELS ---
Generating /alembic/versions/bf942650f62c_automated_db_upgrade.py ...  done
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> bf942650f62c, automated db upgrade
--- MODELS ---
[cont-init.d] 31-migrate: exited 0.
[cont-init.d] 32-env: executing...
Replacing env constants in JS
Processing /app/js/app.fa2b943e.js ...
Processing /app/js/app.fa2b943e.js.map ...
Processing /app/index.html ...
[cont-init.d] 32-env: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO:     Started server process [353]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on unix socket /tmp/gunicorn.sock (Press CTRL+C to quit)`

**Comment by wickedyoda** [comment]
Sounds like from your other issue that you have a networking issue; maybe a firewall or misconfiguration in your setup. If you unable to search because of time-out issues when pinging google and other sites. I would count that your configuration is wrong somewhere or you have a firewall blocking the traffic on your network. Especially considering that you can reach it through the loop back address of 127.0.0.1 which shows it is working but not the IP address assigned to the machine.

**Comment by MaJoRX0** [comment]
> 

srry but how i can fix that ? I'm new to this world :)

**Comment by MaJoRX0** [comment]
well i just double check my firewall even when I type `ufw status` it shows me its inactive but I typed `ufw disable` to make sure and it working fine :) thanks guys

_Originally posted by @MaJoRX0 in https://github.com/searxng/searxng/issues/1561#issuecomment-1196372045_

**Comment by MaJoRX0** [comment]
#https://github.com/searxng/searxng/issues/1561

**Comment by wickedyoda** [comment]
Closing ticket the issue was with the UFW firewall in UBuntu. See referenced ticket above,
