### ISSUE TITLE
[Feature Request] oauth

### ISSUE THREAD

**Issue by aep** [SelfhostedPro/Yacht#506]
Hi. How do you feel about adding oauth as authentication method? This would be defined as env variable I guess, instead of the built-in user login. 

We're happy to either sponsor this feature or contribute it as PR.

**Comment by wickedyoda** [comment]
Feel free to leave some more details, if @SelfhostedPro thinks it works and you can implement it then by all means create a fork, work on it and create a PR. We are always looking for help and others who can contribute.
