### ISSUE TITLE
Project Dead? No Updates for over a year

### ISSUE THREAD

**Issue by potter-jason** [SelfhostedPro/Yacht#508]
Would be sad to see it go, some update from the devs?

**Comment by SelfhostedPro** [comment]
There are plenty of other tickets about this. Work is being done in other branches, it’s just slow currently. Closing duplicate.

**Comment by wickedyoda** [comment]
There has been working performed on the project, this is not dead. However, there has not been a major release the :devel level is the most current on updates. There have been a few of us who have started helping with the project; we welcome others to join as well. We are more active in our discord and you are more than welcome to join and/or contribute to the project.  We could definitely use some help.

**Comment by wickedyoda** [comment]
> There are plenty of other tickets about this. Work is being done in other branches, it’s just slow currently. Closing duplicate.

Not exactly what they were meaning, the main image hasn't been updated in a year.
