### ISSUE TITLE
[Bug Report] yacht have no permission to deploy a Templates

### ISSUE THREAD

**Issue by MaJoRX0** [SelfhostedPro/Yacht#511]
**Describe the bug**
I cant install/deploy any Templates 

**Expected behavior**
i got an error shows that yacht have no permissions to write in the server files

**Screenshots**
![image](https://user-images.githubusercontent.com/45786523/185417586-9920912e-33cd-470f-ae09-32b6d80f3bc9.png)

**Desktop (please complete the following information):**
OS: running yacht on ubuntu server
Browser opera gx
Yacht Version 1.29.2

**Additional context**
how i can give yacht the permissions?

** Logs **
INFO:      - "POST /api/apps/deploy HTTP/1.1" 401 Unauthorized
INFO:      - "POST /api/auth/refresh HTTP/1.1" 200 OK
INFO:      - "POST /api/apps/deploy HTTP/1.1" 500 Internal Server Error

**Comment by wickedyoda** [comment]
That directory is read only for some reason.

**Comment by wickedyoda** [comment]
That would have been my first try, let me try to duplicate the error and get back with you.

**Comment by MaJoRX0** [comment]
> That would have been my first try, let me try to duplicate the error and get back with you.

take ur time 🗡️

**Comment by MaJoRX0** [comment]
i just fixed it by changing Template variables path to another path
