### ISSUE TITLE
[Bug Report] Application deleted upon specific bad configuration.

### ISSUE THREAD

**Issue by ssj4maiko** [SelfhostedPro/Yacht#516]
**Describe the bug**
Reading the documentation on Navidrome, I came to find that it uses a config file for extra configurations, I decided to mirror this file to something I would have access. Essentially, I wanted to make this:

`/path/to/file/navidrome.toml:./navidrome.toml`
(The default location for this file is `./navidrome.toml`

Well, I would get an error saying that `there is no such container` when trying to save. I removed the Volume, and it saved as normal.

So I changed it from `./navidrome.toml` to just `navidrome.toml`, there was no error, but the application was gone. (This was the 2nd time it was gone)

So I have to set everything again, and I guess I won't be able to make this extra volume.

**Raspberry PI 4GB**
 - OS: Raspberry OS
 - Yacht Version: v0.0.7-alpha-2022-07-27--05

**Comment by SelfhostedPro** [comment]
Yacht doesn’t do anything in the background, everything that yacht does requires you to interact with the webui. This is likely an issue with docker.
