### ISSUE TITLE
Yacht not loading on port

### ISSUE THREAD

**Issue by realcharged** [SelfhostedPro/Yacht#521]
ISSUE: Yacht not loading
--
Hey guys, I recently installed Yacht on my Fedora server, but when going to `http://my-ip:8080`, the page doesn't exist. Could someone help me fix this?

**Comment by manishde1234** [comment]
same here page is not loading on the given port

**Comment by farhun1** [comment]
Same with mine fedora server. It says that it is running but page won't work.

**Comment by wickedyoda** [comment]
Guys, we don't check the issues here daily; somehow I have missed this one and will come back when I get home to ask for more details. The quickest way to yacht support is to join our discord.

https://discord.io/selfhostedpros
