### ISSUE TITLE
[Feature Request] Docker-Compose Git Sync

### ISSUE THREAD

**Issue by Ramorous** [SelfhostedPro/Yacht#532]
**Describe the solution you'd like**
Ability to chose to sync your compose yaml and associated files from git per project to allow automation

**Describe alternatives you've considered**
Manually update files from compose directories used/created by yacht

**Comment by SelfhostedPro** [comment]
While it’s not a built in feature, you can use git to clone directly into the compose directory if you mount a volume to your host.

**Comment by Ramorous** [comment]
Yeah, that's what I meant about updating the directories directly
