### ISSUE TITLE
[Bug Report] Yacht Can't Display Containers

### ISSUE THREAD

**Issue by JaxzKyd** [SelfhostedPro/Yacht#533]
**Describe the bug**
After I install Yacht and log in with the default login it won't display any containers. It just gives this error on the website
`Internal Server Error: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))`

**To Reproduce**
1. Install Yacht
2. Login
3. Error would be immediately on the dashboard

**Expected behavior**
I expected to be able to see my docker containers.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 
 - Yacht Version: v0.0.7-alpha-2022-07-27--05

** Logs **
`yacht  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
yacht  | [s6-init] ensuring user provided files have correct perms...exited 0.
yacht  | [fix-attrs.d] applying ownership & permissions fixes...
yacht  | [fix-attrs.d] done.
yacht  | [cont-init.d] executing container initialization scripts...
yacht  | [cont-init.d] 01-envfile: executing...
yacht  | [cont-init.d] 01-envfile: exited 0.
yacht  | [cont-init.d] 02-tamper-check: executing...
yacht  | [cont-init.d] 02-tamper-check: exited 0.
yacht  | [cont-init.d] 10-adduser: executing...
yacht  | usermod: no changes
yacht  |
yacht  | -------------------------------------
yacht  |           _         ()
yacht  |          | |  ___   _    __
yacht  |          | | / __| | |  /  \
yacht  |          | | \__ \ | | | () |
yacht  |          |_| |___/ |_|  \__/
yacht  |
yacht  |
yacht  | Brought to you by linuxserver.io
yacht  | -------------------------------------
yacht  |
yacht  | To support LSIO projects visit:
yacht  | https://www.linuxserver.io/donate/
yacht  | -------------------------------------
yacht  | GID/UID
yacht  | -------------------------------------
yacht  |
yacht  | User uid:    911
yacht  | User gid:    911
yacht  | -------------------------------------
yacht  |
yacht  | [cont-init.d] 10-adduser: exited 0.
yacht  | [cont-init.d] 30-config: executing...
yacht  | [cont-init.d] 30-config: exited 0.
yacht  | [cont-init.d] 31-migrate: executing...
yacht  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
yacht  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
yacht  | INFO  [alembic.autogenerate.compare] Detected added table 'template_variables'
yacht  | INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_variables_replacement' on '['replacement']'
yacht  | INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_variables_variable' on '['variable']'
yacht  | INFO  [alembic.autogenerate.compare] Detected added table 'templates'
yacht  | INFO  [alembic.autogenerate.compare] Detected added index 'ix_templates_title' on '['title']'
yacht  | INFO  [alembic.autogenerate.compare] Detected added table 'user'
yacht  | INFO  [alembic.autogenerate.compare] Detected added index 'ix_user_email' on '['email']'
yacht  | INFO  [alembic.autogenerate.compare] Detected added index 'ix_user_id' on '['id']'
yacht  | INFO  [alembic.autogenerate.compare] Detected added table 'apikeys'
yacht  | INFO  [alembic.autogenerate.compare] Detected added index 'ix_apikeys_id' on '['id']'
yacht  | INFO  [alembic.autogenerate.compare] Detected added index 'ix_apikeys_jti' on '['jti']'
yacht  | INFO  [alembic.autogenerate.compare] Detected added index 'ix_apikeys_key_name' on '['key_name']'
yacht  | INFO  [alembic.autogenerate.compare] Detected added table 'template_item'
yacht  | INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_item_name' on '['name']'
yacht  | INFO  [alembic.autogenerate.compare] Detected added index 'ix_template_item_title' on '['title']'
yacht  | --- MODELS ---
yacht  | Generating /alembic/versions/69ed30794eaf_automated_db_upgrade.py ...  done
yacht  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
yacht  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
yacht  | INFO  [alembic.runtime.migration] Running upgrade  -> 69ed30794eaf, automated db upgrade
yacht  | --- MODELS ---
yacht  | [cont-init.d] 31-migrate: exited 0.
yacht  | [cont-init.d] 32-env: executing...
yacht  | Replacing env constants in JS
yacht  | Processing /app/js/app.37804ef8.js ...
yacht  | Processing /app/js/app.37804ef8.js.map ...
yacht  | Processing /app/index.html ...
yacht  | [cont-init.d] 32-env: exited 0.
yacht  | [cont-init.d] 90-custom-folders: executing...
yacht  | [cont-init.d] 90-custom-folders: exited 0.
yacht  | [cont-init.d] 99-custom-files: executing...
yacht  | [custom-init] no custom files found exiting...
yacht  | [cont-init.d] 99-custom-files: exited 0.
yacht  | [cont-init.d] done.
yacht  | [services.d] starting services
yacht  | [services.d] done.
yacht  | INFO:     Started server process [350]
yacht  | INFO:     Waiting for application startup.
yacht  | INFO:     Application startup complete.
yacht  | INFO:     Uvicorn running on unix socket /tmp/gunicorn.sock (Press CTRL+C to quit)
yacht  | Secret key generated
yacht  | Secret key exists
yacht  | DISABLE_AUTH = False (<class 'bool'>)
yacht  | No Users. Creating the default user.
yacht  | No Variables yet!
yacht  | INFO:      - "GET /api/apps/ HTTP/1.1" 401 Unauthorized
yacht  | INFO:      - "POST /api/auth/refresh HTTP/1.1" 401 Unauthorized
yacht  | INFO:      - "GET /api/auth/me HTTP/1.1" 401 Unauthorized
yacht  | INFO:      - "POST /api/auth/login HTTP/1.1" 200 OK
yacht  | INFO:      - "GET /api/apps/ HTTP/1.1" 500 Internal Server Error`

**Comment by SelfhostedPro** [comment]
Sounds like your user may not have docker permissions to read your apps or your auth token expired. If this is still happening then you'll want to make sure your user has permissions to list docker containers and that you logout and log back into yacht.

**Comment by JaxzKyd** [comment]
How do I grant these grant these permissions?

**Comment by SelfhostedPro** [comment]
You could try using `usermod -aG docker $username` or could look at the permissions stuff in the mac instructions if that doesn’t work: https://yacht.sh/docs/Installation/Mac

**Comment by JaxzKyd** [comment]
Solved!
Adding 
`    environment:
      - PUID=0
      - PGID=0`
Did resolve the issue :D
