### ISSUE TITLE
[Bug Report] Yacht Dashboard Not loading

### ISSUE THREAD

**Issue by fluxkapacitor** [SelfhostedPro/Yacht#538]
**Describe the bug**
Loaded Yacht and logged in, expecting to see my dashboard with metrics although it's empty.

**To Reproduce**
1. Go to Yacht (for me it's http://192.168.4.114:8000/
2. Click on "dashboard"

**Expected behavior**
Expecting to see metrics and usage of my containers, although nothing loads

**Screenshots**
Screenshot attached
![CleanShot 2022-11-10 at 08 08 34@2x](https://user-images.githubusercontent.com/90540099/201100033-d44887a1-9936-4939-9ad1-2a397fecdade.png)

I'm using a new Raspberry Pi 4 - I've got Portainer also running.

**Comment by SelfhostedPro** [comment]
Did you follow the instructions for ARM?
https://yacht.sh/docs/Installation/ARM

**Comment by fluxkapacitor** [comment]
I'm an idiot. Thank you.
