### ISSUE TITLE
When opening any tab on yacht error message Internal Server Error: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))

### ISSUE THREAD

**Issue by Monkeybeam3** [SelfhostedPro/Yacht#541]
I'm running yacht on on my imac late 2015 8 gig ram MacOS monteray version 12.5.1. Whenever I open the control pannel it shows an error message: Internal Server Error: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied')). I have tried rebooting, reinstalling docker and yacht and none of it works. Also, on Docker v4.14.0 and Yacht version 0.0.7-alpha-2022-07-27--05. Any ideas on how to fix? Thanks!

**Comment by wickedyoda** [comment]
Did you do the sudo adduser $user docker and then reboot? This gives your current user docker permissions. Bottom of the main readme file if you need details.

**Comment by SelfhostedPro** [comment]
That looks like there was an issue with the SQLite database. I would export your config in settings, delete the SQLite db in the yacht folder (or all yacht data), and then import into a fresh installation.

**Comment by R-Sharafaldin** [comment]
> That looks like there was an issue with the SQLite database. I would export your config in settings, delete the SQLite db in the yacht folder (or all yacht data), and then import into a fresh installation.

This seems to have fixed the problem for me. I do have another issue now, but I'm gonna troubleshoot by myself a bit, and in any case that's for another topic than this. Thanks for the help though!

**Comment by wickedyoda** [comment]
@R-Sharafaldin Thank you and I will close the issue. If there is anything else feel free to open another ticket or reach out to us on discord.
