### ISSUE TITLE
[Feature Request] Allowing change of default port

### ISSUE THREAD

**Issue by CkR-0ff** [SelfhostedPro/Yacht#546]
**Feature request related to the default port**
I am deploying the container through docker compose but setting as a network already defined ipvlan network.
This way I'm not at liberty to map the port but am forced to use 8000. It'll be a nice addition to be able to set the port of the server for such situations.

**Possible solution**
Maybe having the 8000 value as a default but also allowing it to be changed through environment variable will be a good solution to this.

**Comment by wickedyoda** [comment]
Why would you need to change the internal port, you can change the port on the container by using the -p 8000:8000 as external:internal.

**Comment by SelfhostedPro** [comment]
With IPVLAN they can’t change the port. This was available in an old patch but I removed for some reason. When I finish rewriting the backend I’ll add.
