### ISSUE TITLE
Cannot Log In

### ISSUE THREAD

**Issue by julessilve** [SelfhostedPro/Yacht#554]
Cannot Log Into Yacht

Installed Yacht using:
docker volume create yacht
docker run -d -p 8000:8000 -v /var/run/docker.sock:/var/run/docker.sock -v yacht:/config selfhostedpro/yacht

All installed OK

Trying to log in using:
Once you're at the login page you can login with the username admin@yacht.local and the password pass.

In my case http://admin@192.168.1.101:8000

Get to login screen (see picture) Enter username admin (although it asks for email address - which I gave also) and pass for password. 

No access.
<img width="536" alt="image" src="https://user-images.githubusercontent.com/70835379/208253408-82b35e56-281b-43ee-9582-3ffb2efa6d31.png">

RPi 4 Latest OS lite 64
Docker latest ver
Yacht latest ver

**Comment by rmatte** [comment]
The username is admin@yacht.local, not admin. Try again.

**Comment by wickedyoda** [comment]
Lets show some respect for everyone here, please try the correct user name as per the documentation.

**Comment by rmatte** [comment]
The correct username is admin@yacht.local.
