### ISSUE TITLE
[Bug Report] Theme is set to default

### ISSUE THREAD

**Issue by SebastianGwizdala** [SelfhostedPro/Yacht#557]
When I log in on a new device the theme is set to default and need to set up theme colors again.
Is there an option to set the theme per user rather than per device?

**Comment by wickedyoda** [comment]
It's stored by the cookies in your browser, if they get cleared then it goes back to default.

**Comment by wickedyoda** [comment]
You can make a feature request or if you can program make the change and push it for a merge.

**Comment by wickedyoda** [comment]
@SelfhostedPro feature request
