### ISSUE TITLE
[Bug Report] Environment variable with '=' is displayed incorrectly

### ISSUE THREAD

**Issue by eszkadev** [SelfhostedPro/Yacht#558]
**Describe the bug**
Application view shows environment variable shorter if it contains '=' character.

**To Reproduce**
1. Run docker container outside Yacht: `docker run -t -d -p 127.0.0.1:9980:9980 -e "extra_params=--o:ssl.enable=false" --restart always collabora/code`  (important part is to have env variable with = in the value, like here --o:ssl.enable=false`)
2. Go to Yacht
3. Click on Application -> (your container name)
4. See that in the environment variable info we can see only: `--o:ssl.enable`

**Expected behavior**
It should show in step 4 `--o:ssl.enable=false`

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Yacht Version Any (tested with latest docker and fresh self-build code from repo)

**Comment by wickedyoda** [comment]
Related to the previous issue.

**Comment by SelfhostedPro** [comment]
This is an issue, once I merge the PR referenced this will automatically close. I’ll take a look after the holidays. Thanks for including a PR @eszkadev !
