### ISSUE TITLE
[Bug Report] Internal Server Error: readlink

### ISSUE THREAD

**Issue by el3ctro4ndre** [SelfhostedPro/Yacht#564]
**Describe the bug**
Yacht doesn't shows other docker containers and at avery page of the side menu i get this error:
(image in Screenshots)

**To Reproduce**
1. Install Yacht via docker-compose
2. Open Yacht
3. See error

**Expected behavior**
Yacht loads everything as it should be

**Screenshots**
![image](https://user-images.githubusercontent.com/70718147/210266849-f2b37650-a010-419e-814d-91d5ecbc362f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Browser: Brave Browser
 - Yacht Version: v0.0.7-alpha-2022-07-27--05

**Additional context**
Before the error was "/var/lib/docker/overlay2/l/AY2LK4S6J752HHJOPJ2EJMHUFH" no such file or directory and i manually created the directory

** Logs **
Browser console:

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

docker-compose up's log:

Creating network "yacht_default" with the default driver
Creating yacht ... done
Attaching to yacht
yacht    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
yacht    | [s6-init] ensuring user provided files have correct perms...exited 0.
yacht    | [fix-attrs.d] applying ownership & permissions fixes...
yacht    | [fix-attrs.d] done.
yacht    | [cont-init.d] executing container initialization scripts...
yacht    | [cont-init.d] 01-envfile: executing...
yacht    | [cont-init.d] 01-envfile: exited 0.
yacht    | [cont-init.d] 02-tamper-check: executing...
yacht    | [cont-init.d] 02-tamper-check: exited 0.
yacht    | [cont-init.d] 10-adduser: executing...
yacht    | usermod: no changes
yacht    |
yacht    | -------------------------------------
yacht    |           _         ()
yacht    |          | |  ___   _    __
yacht    |          | | / __| | |  /  \
yacht    |          | | \__ \ | | | () |
yacht    |          |_| |___/ |_|  \__/
yacht    |
yacht    |
yacht    | Brought to you by linuxserver.io
yacht    | -------------------------------------
yacht    |
yacht    | To support LSIO projects visit:
yacht    | https://www.linuxserver.io/donate/
yacht    | -------------------------------------
yacht    | GID/UID
yacht    | -------------------------------------
yacht    |
yacht    | User uid:    911
yacht    | User gid:    911
yacht    | -------------------------------------
yacht    |
yacht    | [cont-init.d] 10-adduser: exited 0.
yacht    | [cont-init.d] 30-config: executing...
yacht    | [cont-init.d] 30-config: exited 0.
yacht    | [cont-init.d] 31-migrate: executing...
yacht    | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
yacht    | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
yacht    | INFO  [alembic.autogenerate.compare] Detected removed index 'ix_jwt_token_blacklist_jti' on 'jwt_token_blacklist'
yacht    | INFO  [alembic.autogenerate.compare] Detected removed table 'jwt_token_blacklist'
yacht    | INFO  [alembic.autogenerate.compare] Detected removed index 'ix_secret_key_key' on 'secret_key'
yacht    | INFO  [alembic.autogenerate.compare] Detected removed table 'secret_key'
yacht    | --- MODELS ---
yacht    | Generating /alembic/versions/4efe40d048d5_automated_db_upgrade.py ...  done
yacht    | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
yacht    | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
yacht    | INFO  [alembic.runtime.migration] Running upgrade  -> 4efe40d048d5, automated db upgrade
yacht    | --- MODELS ---
yacht    | [cont-init.d] 31-migrate: exited 0.
yacht    | [cont-init.d] 32-env: executing...
yacht    | Replacing env constants in JS
yacht    | Processing /app/js/app.37804ef8.js ...
yacht    | Processing /app/js/app.37804ef8.js.map ...
yacht    | Processing /app/index.html ...
yacht    | [cont-init.d] 32-env: exited 0.
yacht    | [cont-init.d] 90-custom-folders: executing...
yacht    | [cont-init.d] 90-custom-folders: exited 0.
yacht    | [cont-init.d] 99-custom-files: executing...
yacht    | [custom-init] no custom files found exiting...
yacht    | [cont-init.d] 99-custom-files: exited 0.
yacht    | [cont-init.d] done.
yacht    | [services.d] starting services
yacht    | [services.d] done.
yacht    | INFO:     Started server process [360]
yacht    | INFO:     Waiting for application startup.
yacht    | INFO:     Application startup complete.
yacht    | INFO:     Uvicorn running on unix socket /tmp/gunicorn.sock (Press CTRL+C to quit)

**Comment by wickedyoda** [comment]
Try removing and adding the container with the yacht:devel tag, it's a level we are using for patches that have not been pushed to the main repo yet. There may be other bugs but this would let us know if it's related to something already addressed.
