### ISSUE TITLE
[Bug Report] Dashboard not loading on amd64 after going back

### ISSUE THREAD

**Issue by Jannik44** [SelfhostedPro/Yacht#573]
**Describe the bug**
Hello, i noticed multiple time that when i click on the dashboard on a container to see stats etc. and stay there for a while and then clock the "back" button to go back on the dashboard the dashboard is empty, i have to reload the entire site to make it work adgain

**To Reproduce**
1. Go to the dashboard
2. Click on a container
3. wait like 10 mins or so
4. click back button

**Screenshots**
![grafik](https://user-images.githubusercontent.com/76906033/213915813-e28b08a9-fb5c-4fc6-92af-04d92499c86c.png)

**Desktop (please complete the following information):**
 - OS: linux Mint
 - Browser Firefox
 - Yacht Version v0.0.7-alpha-2022-07-27--05

**Comment by SelfhostedPro** [comment]
This is because authorization tokens expire fairly quickly (helps prevent access if the access token is stolen by a malicious actor). You can set the following environment variable to a longer time in order to have it not log you out as quickly: 

```
ACCESS_TOKEN_EXPIRES=2592000
```

**Comment by wickedyoda** [comment]
Sorry its taken a little longer to get to your ticket, but the newest work is being done over at https://github.com/SelfhostedPro/yacht-nuxt which is more like a Yacht2.0. The latest image is yacht:devel please try that image and let us know if the problem has been resolved, what was done if it was resolved, or if you still need assistance.

Please update or close the ticket as resolved.

**Comment by Jannik44** [comment]
yeahh... ive switched to portainer since like ... two YEARS?
