### ISSUE TITLE
[Bug Report] DISABLE_AUTH not working

### ISSUE THREAD

**Issue by jrodriguesimg** [SelfhostedPro/Yacht#575]
**Describe the bug**
I passed DISABLE_AUTH to the container but it still asks for authentication

**To Reproduce**
1. create yacht container passing DISABLE_AUTH
```
docker run -d --restart=always  -p 9000:8000 -v /var/run/docker.sock:/var/run/docker.sock -v yacht:/config --name yacht -e DISABLE_AUTH='true' -e SECRET_KEY='secrete' selfhostedpro/yacht
```
2. open localhost:9000

**Expected behavior**
It should not require authentication

**Screenshots**
It requires authentication
<img width="1111" alt="Screenshot 2023-02-03 at 12 34 29" src="https://user-images.githubusercontent.com/39995657/216604987-110372a7-83b9-4895-bfb7-296289811f0e.png">

**Desktop (please complete the following information):**
 - OS: docker for mac on M1 Max, Ventura 13.1
 - Browser: Brave
 - Yacht Version: lastest (IMAGE ID: d79060100eb7) 

**Additional context**
I've never used yatch before. I'm looking for an alternative to portainer that does not require authentication to manage my local docker.

**Comment by faulander** [comment]
i came here for this exact feature which portainer will not implement. So sad to see it's not working :/

**Comment by sutr90** [comment]
@mkoertgen Is the variable value Case sensitive? The OP has lowercase true, as opposed to Pascal case in your example.
