### ISSUE TITLE
[Feature Request] Template App Request: Uptime Kuma

### ISSUE THREAD

**Issue by rmatte** [SelfhostedPro/Yacht#577]
I'm not sure if this is the right place to request this, but it would be great to see Uptime Kuma included in the default templates within Yacht.

https://github.com/louislam/uptime-kuma

It runs on port 3001 by default and the data that should be bound to a directory on the host is in /app/data within the container.

Thanks.

**Comment by mcela** [comment]
+1

Dumping my settings here in case they're useful:

```
General
name: UptimeKuma
image: louislam/uptime-kuma:1

Networking
webui 3001:3001 tcp

Volumes
!config/UptimeKuma /app/data
```

**Comment by wickedyoda** [comment]
Your using the default one provided ?

**Comment by rmatte** [comment]
> Your using the default one provided ?

If you're asking if the one I'm using is the one provided by the project developer, yes it is.

**Comment by wickedyoda** [comment]
Ok, let me look through the repo and update it.

**Comment by wickedyoda** [comment]
I tracked it down, and you're actually on the repo for yacht itself, the repo for the template is over on https://github.com/SelfhostedPro/selfhosted_templates; you can create a branch to make the updates and create a pull request over there to have it updated. I will make a note for him to update it and look at it closer; I do not have access to the repo directly.
