### ISSUE TITLE
[Feature Request] Change login credential to just use a username instead of specifying an email?

### ISSUE THREAD

**Issue by WisdomSky** [SelfhostedPro/Yacht#579]
**Is your feature request related to a problem? Please describe.**
Why does login credentials have to be an email if it's required to be an email at all?

<img width="561" alt="image" src="https://user-images.githubusercontent.com/6792172/222409228-625a5bdd-20aa-404f-8f93-4f6aae589916.png">

Using an actual email (in this case)  for me is stupid (forgive me for the word). Other services I used together with yacht only requires me to provide a username. This is the only one I used where it requires me to put an email instead of just make it having the same username as my other services (whic is usually just "admin").

After hacking through the change user password page, I was able to set it to only simply use `admin`, by opening the devtools and removing the `disabled` class and attributes on the submit button so this means having it as an email is not really required at all. There's not even a forgot password page to make use of that email.

**Comment by gurpal2000** [comment]
Use case is home intranet - don't need to be putting in an email address. Happy with just "admin" ;-)
