### ISSUE TITLE
[Bug Report] Dashboard doesn't load completely on iOS

### ISSUE THREAD

**Issue by itsthejb** [SelfhostedPro/Yacht#586]
**Describe the bug**

(Unfortunately) the complete list of containers fails to load on iOS (WebKit). Tested on Safari and Brave iOS

**To Reproduce**
1. Given reasonably long list of containers (42 in my case)
2. Open in iOS browser (Safari, Brave)
3. Log in
4. Wait a few seconds for containers to load
5. Scroll down

**Expected behavior**
List is "torn" and incomplete

**Screenshots**
![2023-05-09 15-26-59-0](https://github.com/SelfhostedPro/Yacht/assets/557391/f96d6e42-01b7-4da4-a415-fb9d52619957)

**Desktop (please complete the following information):**
 - OS: iOS 16.4.1
 - Browser: Safari
 - Yacht Version: [Docker `selfhostedpro/yacht:latest`](https://hub.docker.com/layers/selfhostedpro/yacht/latest/images/sha256-a2b77a1058c8632b2c0c9c8fa2479388b377b885d4d89f6d9d4d3ea6fbaaeb6d?context=explore)

**Comment by wickedyoda** [comment]
Sorry its taken a little longer to get to your ticket, but the newest work is being done over at https://github.com/SelfhostedPro/yacht-nuxt which is more like a Yacht2.0. The latest image is yacht:devel please try that image and let us know if the problem has been resolved, what was done if it was resolved, or if you still need assistance.

Please update or close the ticket as resolved.
