### ISSUE TITLE
Unexpected Dataloss

### ISSUE THREAD

**Issue by Kovercrosser** [SelfhostedPro/Yacht#587]
**Description**
when there is no disk-space available on the machine and you get into an existing Project, than you klick on edit. even if you change nothing and click submit, then the complete compose File is gone.

**To Reproduce**
1. Fill up all available Disk Space on the Maschine (or where the Volume is saved)
2. Go To Projects, then click on an existing Project
3. Edit the Project
4. Change or don't change anything
5. Click on submit

**Expected Behavior**
I would expect that it doesn't change the file. Or if i edited something that I get an error msg, that there isn't any space available and thus can't be saved. 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser edge

** Logs **
Logs can't be saved because of a Full Disc

**Comment by Kovercrosser** [comment]
This isn't a Problem I currently have. I had it in the Past and lost two docker-comopse files because of it. 
I was investigating an issue (with a other service) and it turned out to be because of the disc space.
I first looked into yacht, and also the project files and then they where gone because of it.
(I know the disc shouldn't get full, but if it happens there also shouldn't be a data loss )

**Comment by wickedyoda** [comment]
The issue is related to low space on the system and docker, not a yacht-related issue.
