### ISSUE TITLE
[Bug Report] nginx reverse proxy. Bad Gateway: undefined 

### ISSUE THREAD

**Issue by mrfluffy-dev** [SelfhostedPro/Yacht#592]
**Describe the bug**
When I revere proxy using nginx proxy manager I get `Bad Gateway: undefined` in a red bar at the bottom.

**To Reproduce**
1. run `docker run -d --network nginx-net -p 8000:8000 -v /var/run/docker.sock:/var/run/docker.sock -v yacht:/config selfhostedpro/yacht`
2. go to 192.168.1.179:8000 (looks good everything works) 
3. setup reverse proxy in nginx proxy manager 
4. go to my.domain.com see yacht open 
5. no containers are listed get error at the bottom `Bad Gateway: undefined`

**Expected behavior**
Yacht loads like it does when going to 192.168.1.179:8000

**Screenshots**
![image](https://github.com/SelfhostedPro/Yacht/assets/53239525/badfb277-5bb8-4300-923f-1abf16f9b818)
![image](https://github.com/SelfhostedPro/Yacht/assets/53239525/285ccd95-6fba-4d82-a032-0d32712c89f1)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS x86_64
 - Browser Brave and FireFox
 - Yacht Version v0.0.7-alpha-2023-01-12--05

**Additional context**
It worked when my network was `bridge`  and I used cloudflare tunnel as a reverse proxy 

** Logs **
```
exports https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:65
    exports https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:102
    onreadystatechange https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:252
    exports https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:252
    exports https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:252
    exports https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:118
    promise callback*0a06/l.prototype.request https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:13
    e https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:13
    exports https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:41
    readApp https://yacht.mrfluffy.xyz/js/app.aad2ad76.js:1
    readApp https://yacht.mrfluffy.xyz/js/app.aad2ad76.js:1
    C https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:73
    dispatch https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:73
    dispatch https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:73
    i https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:73
    created https://yacht.mrfluffy.xyz/js/app.aad2ad76.js:1
    nt https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    Pn https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    _init https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    a https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    sn https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    init https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    n https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    p https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    f https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    Fr https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    _update https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    i https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    get https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    ni https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    On https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    $mount https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    init https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    p https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    f https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
    y https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js:63
[chunk-vendors.5f15452b.js:65:3022](https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js)
Source map error: Error: request failed with status 502
Resource URL: https://yacht.mrfluffy.xyz/js/chunk-vendors.5f15452b.js
Source Map URL: chunk-vendors.5f15452b.js.map

Source map error: Error: request failed with status 502
Resource URL: https://yacht.mrfluffy.xyz/js/app.aad2ad76.js
Source Map URL: app.aad2ad76.js.map
```

**Comment by pbogre** [comment]
getting this as well.

**Comment by QazCetelic** [comment]
I'm also experiencing this issue on `v0.0.7-alpha-2023-01-12--05`

**Comment by wickedyoda** [comment]
Have you all looked at http://dev.yacht.sh/docs/Advanced/Proxy 

I went through and reworked the documentation website, There are old documents on the yacht.sh site, please use the subdomain of dev.yacht.sh, also There is a new version coming out sometime at the end of the year. The main site is not going to be updated until the new version is released. The dev.yacht.sh will remain the temp location for the most current documents. 

Also, try pulling with selfhosted/yacht:devel image; it had lots of fixes applied to it that other images have not. 

These directions are my current setup with a docker host running Debian in AWS with Nginx proxy manager/reverse proxy as a container hosted there as well. It works and passes yacht through just like any other website it's hosting.
