### ISSUE TITLE
[Feature Request] Some sort of App/Template Store

### ISSUE THREAD

**Issue by ajw107** [SelfhostedPro/Yacht#610]
**Is your feature request related to a problem? Please describe.**
Great project, but i feel it's just screaming for some sort of Template/App store.

**Describe the solution you'd like**
A Store section in the UI where you could add a repository (or one controlled by you) so users could submit their templates, and it's just a one-click solution for users to install it (well I say one click, one click and config).  I know someone is already starting work on templating linuxserver.io dockers for instance, and adding their git repo would add them all the Template Store.

**Describe alternatives you've considered**

**Additional context**

**Comment by SelfhostedPro** [comment]
Hey, templates are what fill that role currently or are you looking for something different?

https://yacht.sh/docs/#templates

**Comment by wickedyoda** [comment]
Website correction, @SelfhostedPro remember its a different site now and updated. 

https://dev.yacht.sh/docs/#templates
