### ISSUE TITLE
How to access the running docker shell ?

### ISSUE THREAD

**Issue by patrickelectric** [SelfhostedPro/Yacht#612]
From the interface I was unable to find

**Comment by djripcord** [comment]
Accessing your docker shell can be done as you normally would through docker itself in the command line.
This would look like:
`docker exec -it [CONTAINER NAME] bash`

I prefer bash, but some others like shell, just replace "bash"  with "sh".

**Comment by patrickelectric** [comment]
Is this now available through the interface ?
