### ISSUE TITLE
[Bug Report] Containers not displayed in Yacht

### ISSUE THREAD

**Issue by Zelatrix** [SelfhostedPro/Yacht#636]
**Describe the bug**

I created the Yacht container from the Docker compose on ARM and when it boots, bithing is displayed on the dashboard, but the containers are listed under "applications" 

**To Reproduce**
1. Navigate to the [ip]:port address
2. Log into Yacht
3. No containers are displayed

**Expected behavior**
I expected my containers to be displayed on my dashboard

**Desktop (please complete the following information):**
 - OS: Rapberry Pi OS 
 - Browser: Firefox
 - Yacht Version: v0.0.7-alpha-2023-01-12--05

** Logs **
The tail end of the logs file for the container is:

```
File "/./api/actions/apps.py", line 503, in stat_generator
    current_stats = await process_app_stats(line, app_name)
  File "/./api/actions/apps.py", line 537, in process_app_stats
    mem_current = line["memory_stats"]["usage"]
KeyError: 'usage'
```

**Comment by turbo112** [comment]
Exactly the same here on 2 installations.
Only difference is the docker host OS: It's an Alpine Linux 3.19.0

Any Hint's?

**Comment by KotletJB** [comment]
same issue
