### ISSUE TITLE
Dashboard Ideas

### ISSUE THREAD

**Issue by nashosted** [SelfhostedPro/Yacht#64]
When adding new apps how about having it also add it to the dashboard with the name of the app, CPU and RAM usage and a link to the app. Kind of how Synology does it. See image.

https://i.imgur.com/K4QxWoi.png

**Comment by Griefed** [comment]
Yes, a quick overview of all or chosen containers and their cpu/ram usage would be awesome to have. That's what I'm missing in portainer.

**Comment by SelfhostedPro** [comment]
Hit a road bump in this implementation (having an issue with updating the graphs since the data is nested in an object but I'll figure it out once I focus on this again) so I've shifted my focus to try to build out other areas. I will shift back to this once I've gotten some progress elsewhere.

**Comment by nashosted** [comment]
Progress has been made and the dashboard is now working and has been pushed to master @Griefed please test and evaluate. Thanks @SelfhostedPro!

![image](https://user-images.githubusercontent.com/57927413/93932212-d3dac500-fced-11ea-989c-7ec020f012a8.png)
