### ISSUE TITLE
[Feature Request] App tracking on the template page

### ISSUE THREAD

**Issue by ItsNoted** [SelfhostedPro/Yacht#65]
**Is your feature request related to a problem? Please describe.**
A way to track if we have already installed the app on the template page.

**Describe the solution you'd like**
Maybe a number or some sort of flag showing it's installed on the card on the template page.

**Comment by wickedyoda** [comment]
@geekedtv Please respond and let us know if this ticket is something that still needs to remain open. If not, we can close it due to its age.
