### ISSUE TITLE
[Feature Request] Allow setting default theme via docker compose.

### ISSUE THREAD

**Issue by spthiel** [SelfhostedPro/Yacht#668]
**Is your feature request related to a problem? Please describe.**
I am developing a docker setup for a small team and would like to theme yacht to the default of our project instead of having it default to green

**Describe the solution you'd like**
Some way to set the values of the default theme (i.e. by writing a json to the docker environment variables or storing a file.json somewhere with the theme as content.

**Describe alternatives you've considered**
Alternative would be for each user to set the theme themself but I'd rather if this wasn't required

**Additional context**
\-

**Comment by wickedyoda** [comment]
Please reference https://github.com/SelfhostedPro/yacht-nuxt/issues/2
