### ISSUE TITLE
Any plan for Swarm Support?

### ISSUE THREAD

**Issue by talbaror** [SelfhostedPro/Yacht#682]
Hello,
Yacht is really nice project , but since i run swarm env will be even better , any plan to implement Swarm Support.
I used to use Swarmpit , but its not maintained anymore
Thanks

**Comment by wickedyoda** [comment]
There is a new version in the works, unofficially a Yacht2.0; its found at https://github.com/SelfhostedPro/yacht-nuxt and we are hoping to start incorporating some more features into it in the future.
