### ISSUE TITLE
[Bug Report] Basic auth applied on reverse proxy breaks frontend

### ISSUE THREAD

**Issue by ivancarlosti** [SelfhostedPro/Yacht#683]
**Describe the bug**
When basic auth is enabled on nginx reverse proxy, it breaks Yacht frontend. The login screen returns 
`: Bad Authorization header. Expected value 'Bearer <JWT>'`
on login form after submission.

**To Reproduce**
1. Enable basic authentication on nginx reverse proxy
2. Open frontend URL
3. Try to login

**Expected behavior**
It's expected to run smoothly without error

**Screenshots**
![image](https://github.com/user-attachments/assets/3703727d-b8bb-49c0-b8f1-49338ae615d8)

![image](https://github.com/user-attachments/assets/84c544a4-7b0f-40fc-bb9b-8ae35615193e)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24 Server
 - Browser Chrome
 - Yacht Version v0.0.7-alpha-2023-01-12--05

**Comment by wickedyoda** [comment]
What docker container are you using for nginx? I run linuxserver/nginx:latest and I would have to check my config for the options I have enabled. But I also dont do Auth through Nginx, I let nginx manage my ssl cert and auth is done in yacht.

**Comment by ivancarlosti** [comment]
> What docker container are you using for nginx? I run linuxserver/nginx:latest and I would have to check my config for the options I have enabled. But I also dont do Auth through Nginx, I let nginx manage my ssl cert and auth is done in yacht.

My nginx is not in a container, it comes from CloudPanel installed directly on host OS. It runs very fine without basic auth, my problem is that I want to expose Yacht on the internet but the login form is too insecure, there is no protection layer, 2FA or catcha to avoid bruteforce, so I would like to use basic auth or any other protection layer to protect it.

**Comment by ahobsonsayers** [comment]
I have had this exact issue in the past, but with treafik and basic auth instead of nginx.

It took me a while to find the solution, but eventually discovered that you need to make sure the Authorization header is not being forwarded by your proxy to Yacht.

In traefik this can be done using `removeHeader` in the basic auth middleware configuration options ([docs here](https://doc.traefik.io/traefik/middlewares/http/basicauth/#removeheader)). 

How you doing this in nginx I am not sure, but if feel pretty certain if you do this, your issue will be resolved.

Hope I helped!

**Comment by wickedyoda** [comment]
I just got confirmation a month or so ago about a header line you can put in the yacht page. Doing so disabled local auth so it can be handeld by nginx or other application. Will follow up with directions, if you dont see a msg; then remind me in a couple of days.

**Comment by wickedyoda** [comment]
Normally using reverse proxys these directions are all you need. 

https://yacht.sh/docs/Advanced/Proxy

**Comment by wickedyoda** [comment]
look at env variables here https://github.com/SelfhostedPro/Yacht?tab=readme-ov-file

**Comment by ivancarlosti** [comment]
Just to register, I was unable to make it work. I have [these values on my nginx](https://yacht.sh/docs/Advanced/Proxy/) as default, I would like to not disable local auth as solution :/
