### ISSUE TITLE
Websockets not working behind reverse proxy

### ISSUE THREAD

**Issue by SelfhostedPro** [SelfhostedPro/Yacht#72]
Logs and Stats are blank behind reverse proxy: DOMException: The operation is insecure.

**Comment by lue30499** [comment]
Hello,

I have the same issue. I also have other things running through with socket support completely fine.

![yachtReverseProxyIssue](https://user-images.githubusercontent.com/63104612/94084817-e0743000-fe49-11ea-8097-69d6e6fa8389.png)

Regards,
Lue.

**Comment by SelfhostedPro** [comment]
Yeah, it's due to the fact that yacht is using websockets instead of secure websockets. I'm working on sorting that out. I'll update here once I figure it out.

**Comment by SelfhostedPro** [comment]
Fix is pushed to devel. Once tested I'll push to latest.
