### ISSUE TITLE
[Feature Request] Expand View Applications page

### ISSUE THREAD

**Issue by Griefed** [SelfhostedPro/Yacht#77]
If feasible, I'd love to see the following additions to the "View Applications" page:
Ports:
 - Ports on the host and contaienr in the usual host:container format, for each app.

Stack/Compose:
 - Once compose support is implemented (if I understood that right, that support for compose files is coming), show the stack/compose the container belongs to, if applicable. For Example, on my current prod system, I've got a compose-file in /prosper, so Portainer shows containers as part of stack "prosper".

Columns:
 - Allow users to specify the columns displayed. For example: Only show "Name", "Status", "Ports" & hide "Stack","Image", "Created At". Allows for more personalization, me thinks.

The following is an idea only, not a full on suggestion. Would love your feedback on it.
Colour-coding containers:
In case someone has many containers running, like on my system with currently 28 containers, somehow grouping or identifying them by colour, for example, would be nice. Give all container names which serve websites like wordpress or apache a red background, all container names with containers which serve media a green background. Could be done of a stack by stack basis. Stack A=red, stack B=blue, stack C=green. Much like Portainer displays the state of containers, "running" has a green background. I hope I made sense here. English isn't my first languange, sorry.

**Comment by SelfhostedPro** [comment]
Definitely think these are good. Probably won't be implemented in the alpha build but I'll work towards getting these implemented.

It may be a good idea to separate each of these out into individual issues so that I can keep track of each one individually.

**Comment by Griefed** [comment]
Aight, will do that tomorrow, probably. Thanks. 😀

**Comment by Griefed** [comment]
All points have been moved to their own issues as per your wish. I'm closing this issue.
