### ISSUE TITLE
Log Scrolling

### ISSUE THREAD

**Issue by geekedtv** [SelfhostedPro/Yacht#98]
Logs for apps load from the top rather than the last entry. Scrolling down is needed to see latest entries.

Minor issue.

**Comment by SelfhostedPro** [comment]
This is how they should be presented as that's how you would typically browse logs. I will work on figuring out how to sticky the scrollbar to the the bottom unless someone scrolls up.

**Comment by SelfhostedPro** [comment]
Here's the issue I opened up with vuetify about this:
https://github.com/vuetifyjs/vuetify/issues/12051

**Comment by Griefed** [comment]
"unless someone scrolls up."
Yes please. The auto-scroll in most programs drives me insane, especially if you can't turn it off. If there's an option to toggle it or it automatically stops going to the bottom once you scrolled up, that'd be perfect.

**Comment by SelfhostedPro** [comment]
Yeah. It's going to scroll to the bottom automatically on page load so as logs come in you'll see them and it'll stay with them but once you scroll up it'll stop following. Waiting on Vuetify for now. Also going to be taking the logs at 1000 lines to help with some performance issues.

**Comment by SelfhostedPro** [comment]
This is building in Devel now and when #243 is merged this will be in the main image.
